/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.CalMonthSalesMv;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CalMonthSalesMvRecord extends TableRecordImpl<CalMonthSalesMvRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.CAL_MONTH_SALES_MV.CALENDAR_MONTH_DESC</code>.
     */
    public void setCalendarMonthDesc(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.CAL_MONTH_SALES_MV.CALENDAR_MONTH_DESC</code>.
     */
    public String getCalendarMonthDesc() {
        return (String) get(0);
    }

    /**
     * Setter for <code>SH.CAL_MONTH_SALES_MV.DOLLARS</code>.
     */
    public void setDollars(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.CAL_MONTH_SALES_MV.DOLLARS</code>.
     */
    public BigDecimal getDollars() {
        return (BigDecimal) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CalMonthSalesMvRecord
     */
    public CalMonthSalesMvRecord() {
        super(CalMonthSalesMv.CAL_MONTH_SALES_MV);
    }

    /**
     * Create a detached, initialised CalMonthSalesMvRecord
     */
    public CalMonthSalesMvRecord(String calendarMonthDesc, BigDecimal dollars) {
        super(CalMonthSalesMv.CAL_MONTH_SALES_MV);

        setCalendarMonthDesc(calendarMonthDesc);
        setDollars(dollars);
        resetTouchedOnNotNull();
    }
}
