/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Channels;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChannelsRecord extends UpdatableRecordImpl<ChannelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.CHANNELS.CHANNEL_ID</code>.
     */
    public void setChannelId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.CHANNELS.CHANNEL_ID</code>.
     */
    public Long getChannelId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.CHANNELS.CHANNEL_DESC</code>.
     */
    public void setChannelDesc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.CHANNELS.CHANNEL_DESC</code>.
     */
    public String getChannelDesc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.CHANNELS.CHANNEL_CLASS</code>.
     */
    public void setChannelClass(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.CHANNELS.CHANNEL_CLASS</code>.
     */
    public String getChannelClass() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SH.CHANNELS.CHANNEL_CLASS_ID</code>.
     */
    public void setChannelClassId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.CHANNELS.CHANNEL_CLASS_ID</code>.
     */
    public Long getChannelClassId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>SH.CHANNELS.CHANNEL_TOTAL</code>.
     */
    public void setChannelTotal(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.CHANNELS.CHANNEL_TOTAL</code>.
     */
    public String getChannelTotal() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SH.CHANNELS.CHANNEL_TOTAL_ID</code>.
     */
    public void setChannelTotalId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.CHANNELS.CHANNEL_TOTAL_ID</code>.
     */
    public Long getChannelTotalId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelsRecord
     */
    public ChannelsRecord() {
        super(Channels.CHANNELS);
    }

    /**
     * Create a detached, initialised ChannelsRecord
     */
    public ChannelsRecord(Long channelId, String channelDesc, String channelClass, Long channelClassId, String channelTotal, Long channelTotalId) {
        super(Channels.CHANNELS);

        setChannelId(channelId);
        setChannelDesc(channelDesc);
        setChannelClass(channelClass);
        setChannelClassId(channelClassId);
        setChannelTotal(channelTotal);
        setChannelTotalId(channelTotalId);
        resetTouchedOnNotNull();
    }
}
