/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Costs;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CostsRecord
        extends TableRecordImpl<CostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.COSTS.PROD_ID</code>.
     */
    public void setProdId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.COSTS.PROD_ID</code>.
     */
    public Long getProdId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.COSTS.TIME_ID</code>.
     */
    public void setTimeId(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.COSTS.TIME_ID</code>.
     */
    public LocalDateTime getTimeId() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>SH.COSTS.PROMO_ID</code>.
     */
    public void setPromoId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.COSTS.PROMO_ID</code>.
     */
    public Long getPromoId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>SH.COSTS.CHANNEL_ID</code>.
     */
    public void setChannelId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.COSTS.CHANNEL_ID</code>.
     */
    public Long getChannelId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>SH.COSTS.UNIT_COST</code>.
     */
    public void setUnitCost(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.COSTS.UNIT_COST</code>.
     */
    public BigDecimal getUnitCost() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>SH.COSTS.UNIT_PRICE</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.COSTS.UNIT_PRICE</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CostsRecord
     */
    public CostsRecord() {
        super(Costs.COSTS);
    }

    /**
     * Create a detached, initialised CostsRecord
     */
    public CostsRecord(Long prodId, LocalDateTime timeId, Long promoId, Long channelId, BigDecimal unitCost,
                       BigDecimal unitPrice) {
        super(Costs.COSTS);

        setProdId(prodId);
        setTimeId(timeId);
        setPromoId(promoId);
        setChannelId(channelId);
        setUnitCost(unitCost);
        setUnitPrice(unitPrice);
        resetTouchedOnNotNull();
    }
}
