/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Countries;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountriesRecord extends UpdatableRecordImpl<CountriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_ID</code>.
     */
    public void setCountryId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_ID</code>.
     */
    public Long getCountryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_ISO_CODE</code>.
     */
    public void setCountryIsoCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_ISO_CODE</code>.
     */
    public String getCountryIsoCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_NAME</code>.
     */
    public void setCountryName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_NAME</code>.
     */
    public String getCountryName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_SUBREGION</code>.
     */
    public void setCountrySubregion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_SUBREGION</code>.
     */
    public String getCountrySubregion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_SUBREGION_ID</code>.
     */
    public void setCountrySubregionId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_SUBREGION_ID</code>.
     */
    public Long getCountrySubregionId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_REGION</code>.
     */
    public void setCountryRegion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_REGION</code>.
     */
    public String getCountryRegion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_REGION_ID</code>.
     */
    public void setCountryRegionId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_REGION_ID</code>.
     */
    public Long getCountryRegionId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_TOTAL</code>.
     */
    public void setCountryTotal(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_TOTAL</code>.
     */
    public String getCountryTotal() {
        return (String) get(7);
    }

    /**
     * Setter for <code>SH.COUNTRIES.COUNTRY_TOTAL_ID</code>.
     */
    public void setCountryTotalId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.COUNTRIES.COUNTRY_TOTAL_ID</code>.
     */
    public Long getCountryTotalId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountriesRecord
     */
    public CountriesRecord() {
        super(Countries.COUNTRIES);
    }

    /**
     * Create a detached, initialised CountriesRecord
     */
    public CountriesRecord(Long countryId, String countryIsoCode, String countryName, String countrySubregion, Long countrySubregionId, String countryRegion, Long countryRegionId, String countryTotal, Long countryTotalId) {
        super(Countries.COUNTRIES);

        setCountryId(countryId);
        setCountryIsoCode(countryIsoCode);
        setCountryName(countryName);
        setCountrySubregion(countrySubregion);
        setCountrySubregionId(countrySubregionId);
        setCountryRegion(countryRegion);
        setCountryRegionId(countryRegionId);
        setCountryTotal(countryTotal);
        setCountryTotalId(countryTotalId);
        resetTouchedOnNotNull();
    }
}
