/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Customers;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_ID</code>.
     */
    public void setCustId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_ID</code>.
     */
    public Long getCustId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_FIRST_NAME</code>.
     */
    public void setCustFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_FIRST_NAME</code>.
     */
    public String getCustFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_LAST_NAME</code>.
     */
    public void setCustLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_LAST_NAME</code>.
     */
    public String getCustLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_GENDER</code>.
     */
    public void setCustGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_GENDER</code>.
     */
    public String getCustGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_YEAR_OF_BIRTH</code>.
     */
    public void setCustYearOfBirth(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_YEAR_OF_BIRTH</code>.
     */
    public BigDecimal getCustYearOfBirth() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_MARITAL_STATUS</code>.
     */
    public void setCustMaritalStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_MARITAL_STATUS</code>.
     */
    public String getCustMaritalStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_STREET_ADDRESS</code>.
     */
    public void setCustStreetAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_STREET_ADDRESS</code>.
     */
    public String getCustStreetAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_POSTAL_CODE</code>.
     */
    public void setCustPostalCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_POSTAL_CODE</code>.
     */
    public String getCustPostalCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_CITY</code>.
     */
    public void setCustCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_CITY</code>.
     */
    public String getCustCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_CITY_ID</code>.
     */
    public void setCustCityId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_CITY_ID</code>.
     */
    public Long getCustCityId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_STATE_PROVINCE</code>.
     */
    public void setCustStateProvince(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_STATE_PROVINCE</code>.
     */
    public String getCustStateProvince() {
        return (String) get(10);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_STATE_PROVINCE_ID</code>.
     */
    public void setCustStateProvinceId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_STATE_PROVINCE_ID</code>.
     */
    public Long getCustStateProvinceId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.COUNTRY_ID</code>.
     */
    public void setCountryId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.COUNTRY_ID</code>.
     */
    public Long getCountryId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_MAIN_PHONE_NUMBER</code>.
     */
    public void setCustMainPhoneNumber(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_MAIN_PHONE_NUMBER</code>.
     */
    public String getCustMainPhoneNumber() {
        return (String) get(13);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_INCOME_LEVEL</code>.
     */
    public void setCustIncomeLevel(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_INCOME_LEVEL</code>.
     */
    public String getCustIncomeLevel() {
        return (String) get(14);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_CREDIT_LIMIT</code>.
     */
    public void setCustCreditLimit(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_CREDIT_LIMIT</code>.
     */
    public BigDecimal getCustCreditLimit() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_EMAIL</code>.
     */
    public void setCustEmail(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_EMAIL</code>.
     */
    public String getCustEmail() {
        return (String) get(16);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_TOTAL</code>.
     */
    public void setCustTotal(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_TOTAL</code>.
     */
    public String getCustTotal() {
        return (String) get(17);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_TOTAL_ID</code>.
     */
    public void setCustTotalId(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_TOTAL_ID</code>.
     */
    public Long getCustTotalId() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_SRC_ID</code>.
     */
    public void setCustSrcId(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_SRC_ID</code>.
     */
    public Long getCustSrcId() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_EFF_FROM</code>.
     */
    public void setCustEffFrom(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_EFF_FROM</code>.
     */
    public LocalDateTime getCustEffFrom() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_EFF_TO</code>.
     */
    public void setCustEffTo(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_EFF_TO</code>.
     */
    public LocalDateTime getCustEffTo() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>SH.CUSTOMERS.CUST_VALID</code>.
     */
    public void setCustValid(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>SH.CUSTOMERS.CUST_VALID</code>.
     */
    public String getCustValid() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Long custId, String custFirstName, String custLastName, String custGender, BigDecimal custYearOfBirth, String custMaritalStatus, String custStreetAddress, String custPostalCode, String custCity, Long custCityId, String custStateProvince, Long custStateProvinceId, Long countryId, String custMainPhoneNumber, String custIncomeLevel, BigDecimal custCreditLimit, String custEmail, String custTotal, Long custTotalId, Long custSrcId, LocalDateTime custEffFrom, LocalDateTime custEffTo, String custValid) {
        super(Customers.CUSTOMERS);

        setCustId(custId);
        setCustFirstName(custFirstName);
        setCustLastName(custLastName);
        setCustGender(custGender);
        setCustYearOfBirth(custYearOfBirth);
        setCustMaritalStatus(custMaritalStatus);
        setCustStreetAddress(custStreetAddress);
        setCustPostalCode(custPostalCode);
        setCustCity(custCity);
        setCustCityId(custCityId);
        setCustStateProvince(custStateProvince);
        setCustStateProvinceId(custStateProvinceId);
        setCountryId(countryId);
        setCustMainPhoneNumber(custMainPhoneNumber);
        setCustIncomeLevel(custIncomeLevel);
        setCustCreditLimit(custCreditLimit);
        setCustEmail(custEmail);
        setCustTotal(custTotal);
        setCustTotalId(custTotalId);
        setCustSrcId(custSrcId);
        setCustEffFrom(custEffFrom);
        setCustEffTo(custEffTo);
        setCustValid(custValid);
        resetTouchedOnNotNull();
    }
}
