/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.FweekPscatSalesMv;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class FweekPscatSalesMvRecord
        extends TableRecordImpl<FweekPscatSalesMvRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.FWEEK_PSCAT_SALES_MV.WEEK_ENDING_DAY</code>.
     */
    public void setWeekEndingDay(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.FWEEK_PSCAT_SALES_MV.WEEK_ENDING_DAY</code>.
     */
    public LocalDateTime getWeekEndingDay() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>SH.FWEEK_PSCAT_SALES_MV.PROD_SUBCATEGORY</code>.
     */
    public void setProdSubcategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.FWEEK_PSCAT_SALES_MV.PROD_SUBCATEGORY</code>.
     */
    public String getProdSubcategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.FWEEK_PSCAT_SALES_MV.DOLLARS</code>.
     */
    public void setDollars(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.FWEEK_PSCAT_SALES_MV.DOLLARS</code>.
     */
    public BigDecimal getDollars() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>SH.FWEEK_PSCAT_SALES_MV.CHANNEL_ID</code>.
     */
    public void setChannelId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.FWEEK_PSCAT_SALES_MV.CHANNEL_ID</code>.
     */
    public Long getChannelId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>SH.FWEEK_PSCAT_SALES_MV.PROMO_ID</code>.
     */
    public void setPromoId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.FWEEK_PSCAT_SALES_MV.PROMO_ID</code>.
     */
    public Long getPromoId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FweekPscatSalesMvRecord
     */
    public FweekPscatSalesMvRecord() {
        super(FweekPscatSalesMv.FWEEK_PSCAT_SALES_MV);
    }

    /**
     * Create a detached, initialised FweekPscatSalesMvRecord
     */
    public FweekPscatSalesMvRecord(LocalDateTime weekEndingDay, String prodSubcategory, BigDecimal dollars,
                                   Long channelId, Long promoId) {
        super(FweekPscatSalesMv.FWEEK_PSCAT_SALES_MV);

        setWeekEndingDay(weekEndingDay);
        setProdSubcategory(prodSubcategory);
        setDollars(dollars);
        setChannelId(channelId);
        setPromoId(promoId);
        resetTouchedOnNotNull();
    }
}
