/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Products;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.PRODUCTS.PROD_ID</code>.
     */
    public void setProdId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_ID</code>.
     */
    public Long getProdId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_NAME</code>.
     */
    public void setProdName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_NAME</code>.
     */
    public String getProdName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_DESC</code>.
     */
    public void setProdDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_DESC</code>.
     */
    public String getProdDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_SUBCATEGORY</code>.
     */
    public void setProdSubcategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_SUBCATEGORY</code>.
     */
    public String getProdSubcategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_SUBCATEGORY_ID</code>.
     */
    public void setProdSubcategoryId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_SUBCATEGORY_ID</code>.
     */
    public Long getProdSubcategoryId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_SUBCATEGORY_DESC</code>.
     */
    public void setProdSubcategoryDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_SUBCATEGORY_DESC</code>.
     */
    public String getProdSubcategoryDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_CATEGORY</code>.
     */
    public void setProdCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_CATEGORY</code>.
     */
    public String getProdCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_CATEGORY_ID</code>.
     */
    public void setProdCategoryId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_CATEGORY_ID</code>.
     */
    public Long getProdCategoryId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_CATEGORY_DESC</code>.
     */
    public void setProdCategoryDesc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_CATEGORY_DESC</code>.
     */
    public String getProdCategoryDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_WEIGHT_CLASS</code>.
     */
    public void setProdWeightClass(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_WEIGHT_CLASS</code>.
     */
    public BigDecimal getProdWeightClass() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_UNIT_OF_MEASURE</code>.
     */
    public void setProdUnitOfMeasure(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_UNIT_OF_MEASURE</code>.
     */
    public String getProdUnitOfMeasure() {
        return (String) get(10);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_PACK_SIZE</code>.
     */
    public void setProdPackSize(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_PACK_SIZE</code>.
     */
    public String getProdPackSize() {
        return (String) get(11);
    }

    /**
     * Setter for <code>SH.PRODUCTS.SUPPLIER_ID</code>.
     */
    public void setSupplierId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.SUPPLIER_ID</code>.
     */
    public Long getSupplierId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_STATUS</code>.
     */
    public void setProdStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_STATUS</code>.
     */
    public String getProdStatus() {
        return (String) get(13);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_LIST_PRICE</code>.
     */
    public void setProdListPrice(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_LIST_PRICE</code>.
     */
    public BigDecimal getProdListPrice() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_MIN_PRICE</code>.
     */
    public void setProdMinPrice(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_MIN_PRICE</code>.
     */
    public BigDecimal getProdMinPrice() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_TOTAL</code>.
     */
    public void setProdTotal(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_TOTAL</code>.
     */
    public String getProdTotal() {
        return (String) get(16);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_TOTAL_ID</code>.
     */
    public void setProdTotalId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_TOTAL_ID</code>.
     */
    public Long getProdTotalId() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_SRC_ID</code>.
     */
    public void setProdSrcId(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_SRC_ID</code>.
     */
    public Long getProdSrcId() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_EFF_FROM</code>.
     */
    public void setProdEffFrom(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_EFF_FROM</code>.
     */
    public LocalDateTime getProdEffFrom() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_EFF_TO</code>.
     */
    public void setProdEffTo(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_EFF_TO</code>.
     */
    public LocalDateTime getProdEffTo() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>SH.PRODUCTS.PROD_VALID</code>.
     */
    public void setProdValid(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>SH.PRODUCTS.PROD_VALID</code>.
     */
    public String getProdValid() {
        return (String) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Long prodId, String prodName, String prodDesc, String prodSubcategory, Long prodSubcategoryId, String prodSubcategoryDesc, String prodCategory, Long prodCategoryId, String prodCategoryDesc, BigDecimal prodWeightClass, String prodUnitOfMeasure, String prodPackSize, Long supplierId, String prodStatus, BigDecimal prodListPrice, BigDecimal prodMinPrice, String prodTotal, Long prodTotalId, Long prodSrcId, LocalDateTime prodEffFrom, LocalDateTime prodEffTo, String prodValid) {
        super(Products.PRODUCTS);

        setProdId(prodId);
        setProdName(prodName);
        setProdDesc(prodDesc);
        setProdSubcategory(prodSubcategory);
        setProdSubcategoryId(prodSubcategoryId);
        setProdSubcategoryDesc(prodSubcategoryDesc);
        setProdCategory(prodCategory);
        setProdCategoryId(prodCategoryId);
        setProdCategoryDesc(prodCategoryDesc);
        setProdWeightClass(prodWeightClass);
        setProdUnitOfMeasure(prodUnitOfMeasure);
        setProdPackSize(prodPackSize);
        setSupplierId(supplierId);
        setProdStatus(prodStatus);
        setProdListPrice(prodListPrice);
        setProdMinPrice(prodMinPrice);
        setProdTotal(prodTotal);
        setProdTotalId(prodTotalId);
        setProdSrcId(prodSrcId);
        setProdEffFrom(prodEffFrom);
        setProdEffTo(prodEffTo);
        setProdValid(prodValid);
        resetTouchedOnNotNull();
    }
}
