/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Profits;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProfitsRecord
        extends TableRecordImpl<ProfitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.PROFITS.CHANNEL_ID</code>.
     */
    public void setChannelId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.PROFITS.CHANNEL_ID</code>.
     */
    public Long getChannelId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.PROFITS.CUST_ID</code>.
     */
    public void setCustId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.PROFITS.CUST_ID</code>.
     */
    public Long getCustId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>SH.PROFITS.PROD_ID</code>.
     */
    public void setProdId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.PROFITS.PROD_ID</code>.
     */
    public Long getProdId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>SH.PROFITS.PROMO_ID</code>.
     */
    public void setPromoId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.PROFITS.PROMO_ID</code>.
     */
    public Long getPromoId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>SH.PROFITS.TIME_ID</code>.
     */
    public void setTimeId(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.PROFITS.TIME_ID</code>.
     */
    public LocalDateTime getTimeId() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>SH.PROFITS.UNIT_COST</code>.
     */
    public void setUnitCost(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.PROFITS.UNIT_COST</code>.
     */
    public BigDecimal getUnitCost() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>SH.PROFITS.UNIT_PRICE</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.PROFITS.UNIT_PRICE</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>SH.PROFITS.AMOUNT_SOLD</code>.
     */
    public void setAmountSold(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.PROFITS.AMOUNT_SOLD</code>.
     */
    public BigDecimal getAmountSold() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>SH.PROFITS.QUANTITY_SOLD</code>.
     */
    public void setQuantitySold(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.PROFITS.QUANTITY_SOLD</code>.
     */
    public BigDecimal getQuantitySold() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>SH.PROFITS.TOTAL_COST</code>.
     */
    public void setTotalCost(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>SH.PROFITS.TOTAL_COST</code>.
     */
    public BigDecimal getTotalCost() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfitsRecord
     */
    public ProfitsRecord() {
        super(Profits.PROFITS);
    }

    /**
     * Create a detached, initialised ProfitsRecord
     */
    public ProfitsRecord(Long channelId, Long custId, Long prodId, Long promoId, LocalDateTime timeId,
                         BigDecimal unitCost, BigDecimal unitPrice, BigDecimal amountSold, BigDecimal quantitySold,
                         BigDecimal totalCost) {
        super(Profits.PROFITS);

        setChannelId(channelId);
        setCustId(custId);
        setProdId(prodId);
        setPromoId(promoId);
        setTimeId(timeId);
        setUnitCost(unitCost);
        setUnitPrice(unitPrice);
        setAmountSold(amountSold);
        setQuantitySold(quantitySold);
        setTotalCost(totalCost);
        resetTouchedOnNotNull();
    }
}
