/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Promotions;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PromotionsRecord
        extends UpdatableRecordImpl<PromotionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_ID</code>.
     */
    public void setPromoId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_ID</code>.
     */
    public Long getPromoId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_NAME</code>.
     */
    public void setPromoName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_NAME</code>.
     */
    public String getPromoName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_SUBCATEGORY</code>.
     */
    public void setPromoSubcategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_SUBCATEGORY</code>.
     */
    public String getPromoSubcategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_SUBCATEGORY_ID</code>.
     */
    public void setPromoSubcategoryId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_SUBCATEGORY_ID</code>.
     */
    public Long getPromoSubcategoryId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_CATEGORY</code>.
     */
    public void setPromoCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_CATEGORY</code>.
     */
    public String getPromoCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_CATEGORY_ID</code>.
     */
    public void setPromoCategoryId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_CATEGORY_ID</code>.
     */
    public Long getPromoCategoryId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_COST</code>.
     */
    public void setPromoCost(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_COST</code>.
     */
    public BigDecimal getPromoCost() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_BEGIN_DATE</code>.
     */
    public void setPromoBeginDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_BEGIN_DATE</code>.
     */
    public LocalDateTime getPromoBeginDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_END_DATE</code>.
     */
    public void setPromoEndDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_END_DATE</code>.
     */
    public LocalDateTime getPromoEndDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_TOTAL</code>.
     */
    public void setPromoTotal(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_TOTAL</code>.
     */
    public String getPromoTotal() {
        return (String) get(9);
    }

    /**
     * Setter for <code>SH.PROMOTIONS.PROMO_TOTAL_ID</code>.
     */
    public void setPromoTotalId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>SH.PROMOTIONS.PROMO_TOTAL_ID</code>.
     */
    public Long getPromoTotalId() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PromotionsRecord
     */
    public PromotionsRecord() {
        super(Promotions.PROMOTIONS);
    }

    /**
     * Create a detached, initialised PromotionsRecord
     */
    public PromotionsRecord(Long promoId, String promoName, String promoSubcategory, Long promoSubcategoryId,
                            String promoCategory, Long promoCategoryId, BigDecimal promoCost,
                            LocalDateTime promoBeginDate, LocalDateTime promoEndDate, String promoTotal,
                            Long promoTotalId) {
        super(Promotions.PROMOTIONS);

        setPromoId(promoId);
        setPromoName(promoName);
        setPromoSubcategory(promoSubcategory);
        setPromoSubcategoryId(promoSubcategoryId);
        setPromoCategory(promoCategory);
        setPromoCategoryId(promoCategoryId);
        setPromoCost(promoCost);
        setPromoBeginDate(promoBeginDate);
        setPromoEndDate(promoEndDate);
        setPromoTotal(promoTotal);
        setPromoTotalId(promoTotalId);
        resetTouchedOnNotNull();
    }
}
