/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Sales;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class SalesRecord
        extends TableRecordImpl<SalesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.SALES.PROD_ID</code>.
     */
    public void setProdId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.SALES.PROD_ID</code>.
     */
    public Long getProdId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.SALES.CUST_ID</code>.
     */
    public void setCustId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.SALES.CUST_ID</code>.
     */
    public Long getCustId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>SH.SALES.TIME_ID</code>.
     */
    public void setTimeId(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.SALES.TIME_ID</code>.
     */
    public LocalDateTime getTimeId() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>SH.SALES.CHANNEL_ID</code>.
     */
    public void setChannelId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.SALES.CHANNEL_ID</code>.
     */
    public Long getChannelId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>SH.SALES.PROMO_ID</code>.
     */
    public void setPromoId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.SALES.PROMO_ID</code>.
     */
    public Long getPromoId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>SH.SALES.QUANTITY_SOLD</code>.
     */
    public void setQuantitySold(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.SALES.QUANTITY_SOLD</code>.
     */
    public BigDecimal getQuantitySold() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>SH.SALES.AMOUNT_SOLD</code>.
     */
    public void setAmountSold(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.SALES.AMOUNT_SOLD</code>.
     */
    public BigDecimal getAmountSold() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesRecord
     */
    public SalesRecord() {
        super(Sales.SALES);
    }

    /**
     * Create a detached, initialised SalesRecord
     */
    public SalesRecord(Long prodId, Long custId, LocalDateTime timeId, Long channelId, Long promoId,
                       BigDecimal quantitySold, BigDecimal amountSold) {
        super(Sales.SALES);

        setProdId(prodId);
        setCustId(custId);
        setTimeId(timeId);
        setChannelId(channelId);
        setPromoId(promoId);
        setQuantitySold(quantitySold);
        setAmountSold(amountSold);
        resetTouchedOnNotNull();
    }
}
