/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.SupplementaryDemographics;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class SupplementaryDemographicsRecord
        extends UpdatableRecordImpl<SupplementaryDemographicsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.CUST_ID</code>.
     */
    public void setCustId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.CUST_ID</code>.
     */
    public Long getCustId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.EDUCATION</code>.
     */
    public void setEducation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.EDUCATION</code>.
     */
    public String getEducation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.OCCUPATION</code>.
     */
    public void setOccupation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.OCCUPATION</code>.
     */
    public String getOccupation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.HOUSEHOLD_SIZE</code>.
     */
    public void setHouseholdSize(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.HOUSEHOLD_SIZE</code>.
     */
    public String getHouseholdSize() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.YRS_RESIDENCE</code>.
     */
    public void setYrsResidence(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.YRS_RESIDENCE</code>.
     */
    public BigDecimal getYrsResidence() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.AFFINITY_CARD</code>.
     */
    public void setAffinityCard(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.AFFINITY_CARD</code>.
     */
    public BigDecimal getAffinityCard() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.CRICKET</code>.
     */
    public void setCricket(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.CRICKET</code>.
     */
    public BigDecimal getCricket() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.BASEBALL</code>.
     */
    public void setBaseball(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.BASEBALL</code>.
     */
    public BigDecimal getBaseball() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.TENNIS</code>.
     */
    public void setTennis(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.TENNIS</code>.
     */
    public BigDecimal getTennis() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.SOCCER</code>.
     */
    public void setSoccer(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.SOCCER</code>.
     */
    public BigDecimal getSoccer() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.GOLF</code>.
     */
    public void setGolf(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.GOLF</code>.
     */
    public BigDecimal getGolf() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.UNKNOWN</code>.
     */
    public void setUnknown(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.UNKNOWN</code>.
     */
    public BigDecimal getUnknown() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.MISC</code>.
     */
    public void setMisc(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.MISC</code>.
     */
    public BigDecimal getMisc() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.COMMENTS</code>.
     */
    public void setComments(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.COMMENTS</code>.
     */
    public String getComments() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplementaryDemographicsRecord
     */
    public SupplementaryDemographicsRecord() {
        super(SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS);
    }

    /**
     * Create a detached, initialised SupplementaryDemographicsRecord
     */
    public SupplementaryDemographicsRecord(Long custId, String education, String occupation, String householdSize,
                                           BigDecimal yrsResidence, BigDecimal affinityCard, BigDecimal cricket,
                                           BigDecimal baseball, BigDecimal tennis, BigDecimal soccer, BigDecimal golf,
                                           BigDecimal unknown, BigDecimal misc, String comments) {
        super(SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS);

        setCustId(custId);
        setEducation(education);
        setOccupation(occupation);
        setHouseholdSize(householdSize);
        setYrsResidence(yrsResidence);
        setAffinityCard(affinityCard);
        setCricket(cricket);
        setBaseball(baseball);
        setTennis(tennis);
        setSoccer(soccer);
        setGolf(golf);
        setUnknown(unknown);
        setMisc(misc);
        setComments(comments);
        resetTouchedOnNotNull();
    }
}
