/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Times;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TimesRecord extends UpdatableRecordImpl<TimesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SH.TIMES.TIME_ID</code>.
     */
    public void setTimeId(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>SH.TIMES.TIME_ID</code>.
     */
    public LocalDateTime getTimeId() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>SH.TIMES.DAY_NAME</code>.
     */
    public void setDayName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAY_NAME</code>.
     */
    public String getDayName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SH.TIMES.DAY_NUMBER_IN_WEEK</code>.
     */
    public void setDayNumberInWeek(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAY_NUMBER_IN_WEEK</code>.
     */
    public BigDecimal getDayNumberInWeek() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>SH.TIMES.DAY_NUMBER_IN_MONTH</code>.
     */
    public void setDayNumberInMonth(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAY_NUMBER_IN_MONTH</code>.
     */
    public BigDecimal getDayNumberInMonth() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_WEEK_NUMBER</code>.
     */
    public void setCalendarWeekNumber(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_WEEK_NUMBER</code>.
     */
    public BigDecimal getCalendarWeekNumber() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_WEEK_NUMBER</code>.
     */
    public void setFiscalWeekNumber(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_WEEK_NUMBER</code>.
     */
    public BigDecimal getFiscalWeekNumber() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>SH.TIMES.WEEK_ENDING_DAY</code>.
     */
    public void setWeekEndingDay(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>SH.TIMES.WEEK_ENDING_DAY</code>.
     */
    public LocalDateTime getWeekEndingDay() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>SH.TIMES.WEEK_ENDING_DAY_ID</code>.
     */
    public void setWeekEndingDayId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>SH.TIMES.WEEK_ENDING_DAY_ID</code>.
     */
    public Long getWeekEndingDayId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_MONTH_NUMBER</code>.
     */
    public void setCalendarMonthNumber(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_MONTH_NUMBER</code>.
     */
    public BigDecimal getCalendarMonthNumber() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_MONTH_NUMBER</code>.
     */
    public void setFiscalMonthNumber(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_MONTH_NUMBER</code>.
     */
    public BigDecimal getFiscalMonthNumber() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_MONTH_DESC</code>.
     */
    public void setCalendarMonthDesc(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_MONTH_DESC</code>.
     */
    public String getCalendarMonthDesc() {
        return (String) get(10);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_MONTH_ID</code>.
     */
    public void setCalendarMonthId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_MONTH_ID</code>.
     */
    public Long getCalendarMonthId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_MONTH_DESC</code>.
     */
    public void setFiscalMonthDesc(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_MONTH_DESC</code>.
     */
    public String getFiscalMonthDesc() {
        return (String) get(12);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_MONTH_ID</code>.
     */
    public void setFiscalMonthId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_MONTH_ID</code>.
     */
    public Long getFiscalMonthId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>SH.TIMES.DAYS_IN_CAL_MONTH</code>.
     */
    public void setDaysInCalMonth(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAYS_IN_CAL_MONTH</code>.
     */
    public BigDecimal getDaysInCalMonth() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>SH.TIMES.DAYS_IN_FIS_MONTH</code>.
     */
    public void setDaysInFisMonth(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAYS_IN_FIS_MONTH</code>.
     */
    public BigDecimal getDaysInFisMonth() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>SH.TIMES.END_OF_CAL_MONTH</code>.
     */
    public void setEndOfCalMonth(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>SH.TIMES.END_OF_CAL_MONTH</code>.
     */
    public LocalDateTime getEndOfCalMonth() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>SH.TIMES.END_OF_FIS_MONTH</code>.
     */
    public void setEndOfFisMonth(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>SH.TIMES.END_OF_FIS_MONTH</code>.
     */
    public LocalDateTime getEndOfFisMonth() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_MONTH_NAME</code>.
     */
    public void setCalendarMonthName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_MONTH_NAME</code>.
     */
    public String getCalendarMonthName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_MONTH_NAME</code>.
     */
    public void setFiscalMonthName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_MONTH_NAME</code>.
     */
    public String getFiscalMonthName() {
        return (String) get(19);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_QUARTER_DESC</code>.
     */
    public void setCalendarQuarterDesc(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_QUARTER_DESC</code>.
     */
    public String getCalendarQuarterDesc() {
        return (String) get(20);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_QUARTER_ID</code>.
     */
    public void setCalendarQuarterId(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_QUARTER_ID</code>.
     */
    public Long getCalendarQuarterId() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_QUARTER_DESC</code>.
     */
    public void setFiscalQuarterDesc(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_QUARTER_DESC</code>.
     */
    public String getFiscalQuarterDesc() {
        return (String) get(22);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_QUARTER_ID</code>.
     */
    public void setFiscalQuarterId(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_QUARTER_ID</code>.
     */
    public Long getFiscalQuarterId() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>SH.TIMES.DAYS_IN_CAL_QUARTER</code>.
     */
    public void setDaysInCalQuarter(BigDecimal value) {
        set(24, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAYS_IN_CAL_QUARTER</code>.
     */
    public BigDecimal getDaysInCalQuarter() {
        return (BigDecimal) get(24);
    }

    /**
     * Setter for <code>SH.TIMES.DAYS_IN_FIS_QUARTER</code>.
     */
    public void setDaysInFisQuarter(BigDecimal value) {
        set(25, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAYS_IN_FIS_QUARTER</code>.
     */
    public BigDecimal getDaysInFisQuarter() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for <code>SH.TIMES.END_OF_CAL_QUARTER</code>.
     */
    public void setEndOfCalQuarter(LocalDateTime value) {
        set(26, value);
    }

    /**
     * Getter for <code>SH.TIMES.END_OF_CAL_QUARTER</code>.
     */
    public LocalDateTime getEndOfCalQuarter() {
        return (LocalDateTime) get(26);
    }

    /**
     * Setter for <code>SH.TIMES.END_OF_FIS_QUARTER</code>.
     */
    public void setEndOfFisQuarter(LocalDateTime value) {
        set(27, value);
    }

    /**
     * Getter for <code>SH.TIMES.END_OF_FIS_QUARTER</code>.
     */
    public LocalDateTime getEndOfFisQuarter() {
        return (LocalDateTime) get(27);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_QUARTER_NUMBER</code>.
     */
    public void setCalendarQuarterNumber(BigDecimal value) {
        set(28, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_QUARTER_NUMBER</code>.
     */
    public BigDecimal getCalendarQuarterNumber() {
        return (BigDecimal) get(28);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_QUARTER_NUMBER</code>.
     */
    public void setFiscalQuarterNumber(BigDecimal value) {
        set(29, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_QUARTER_NUMBER</code>.
     */
    public BigDecimal getFiscalQuarterNumber() {
        return (BigDecimal) get(29);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_YEAR</code>.
     */
    public void setCalendarYear(BigDecimal value) {
        set(30, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_YEAR</code>.
     */
    public BigDecimal getCalendarYear() {
        return (BigDecimal) get(30);
    }

    /**
     * Setter for <code>SH.TIMES.CALENDAR_YEAR_ID</code>.
     */
    public void setCalendarYearId(Long value) {
        set(31, value);
    }

    /**
     * Getter for <code>SH.TIMES.CALENDAR_YEAR_ID</code>.
     */
    public Long getCalendarYearId() {
        return (Long) get(31);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_YEAR</code>.
     */
    public void setFiscalYear(BigDecimal value) {
        set(32, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_YEAR</code>.
     */
    public BigDecimal getFiscalYear() {
        return (BigDecimal) get(32);
    }

    /**
     * Setter for <code>SH.TIMES.FISCAL_YEAR_ID</code>.
     */
    public void setFiscalYearId(Long value) {
        set(33, value);
    }

    /**
     * Getter for <code>SH.TIMES.FISCAL_YEAR_ID</code>.
     */
    public Long getFiscalYearId() {
        return (Long) get(33);
    }

    /**
     * Setter for <code>SH.TIMES.DAYS_IN_CAL_YEAR</code>.
     */
    public void setDaysInCalYear(BigDecimal value) {
        set(34, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAYS_IN_CAL_YEAR</code>.
     */
    public BigDecimal getDaysInCalYear() {
        return (BigDecimal) get(34);
    }

    /**
     * Setter for <code>SH.TIMES.DAYS_IN_FIS_YEAR</code>.
     */
    public void setDaysInFisYear(BigDecimal value) {
        set(35, value);
    }

    /**
     * Getter for <code>SH.TIMES.DAYS_IN_FIS_YEAR</code>.
     */
    public BigDecimal getDaysInFisYear() {
        return (BigDecimal) get(35);
    }

    /**
     * Setter for <code>SH.TIMES.END_OF_CAL_YEAR</code>.
     */
    public void setEndOfCalYear(LocalDateTime value) {
        set(36, value);
    }

    /**
     * Getter for <code>SH.TIMES.END_OF_CAL_YEAR</code>.
     */
    public LocalDateTime getEndOfCalYear() {
        return (LocalDateTime) get(36);
    }

    /**
     * Setter for <code>SH.TIMES.END_OF_FIS_YEAR</code>.
     */
    public void setEndOfFisYear(LocalDateTime value) {
        set(37, value);
    }

    /**
     * Getter for <code>SH.TIMES.END_OF_FIS_YEAR</code>.
     */
    public LocalDateTime getEndOfFisYear() {
        return (LocalDateTime) get(37);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<LocalDateTime> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimesRecord
     */
    public TimesRecord() {
        super(Times.TIMES);
    }

    /**
     * Create a detached, initialised TimesRecord
     */
    public TimesRecord(LocalDateTime timeId, String dayName, BigDecimal dayNumberInWeek, BigDecimal dayNumberInMonth, BigDecimal calendarWeekNumber, BigDecimal fiscalWeekNumber, LocalDateTime weekEndingDay, Long weekEndingDayId, BigDecimal calendarMonthNumber, BigDecimal fiscalMonthNumber, String calendarMonthDesc, Long calendarMonthId, String fiscalMonthDesc, Long fiscalMonthId, BigDecimal daysInCalMonth, BigDecimal daysInFisMonth, LocalDateTime endOfCalMonth, LocalDateTime endOfFisMonth, String calendarMonthName, String fiscalMonthName, String calendarQuarterDesc, Long calendarQuarterId, String fiscalQuarterDesc, Long fiscalQuarterId, BigDecimal daysInCalQuarter, BigDecimal daysInFisQuarter, LocalDateTime endOfCalQuarter, LocalDateTime endOfFisQuarter, BigDecimal calendarQuarterNumber, BigDecimal fiscalQuarterNumber, BigDecimal calendarYear, Long calendarYearId, BigDecimal fiscalYear, Long fiscalYearId, BigDecimal daysInCalYear, BigDecimal daysInFisYear, LocalDateTime endOfCalYear, LocalDateTime endOfFisYear) {
        super(Times.TIMES);

        setTimeId(timeId);
        setDayName(dayName);
        setDayNumberInWeek(dayNumberInWeek);
        setDayNumberInMonth(dayNumberInMonth);
        setCalendarWeekNumber(calendarWeekNumber);
        setFiscalWeekNumber(fiscalWeekNumber);
        setWeekEndingDay(weekEndingDay);
        setWeekEndingDayId(weekEndingDayId);
        setCalendarMonthNumber(calendarMonthNumber);
        setFiscalMonthNumber(fiscalMonthNumber);
        setCalendarMonthDesc(calendarMonthDesc);
        setCalendarMonthId(calendarMonthId);
        setFiscalMonthDesc(fiscalMonthDesc);
        setFiscalMonthId(fiscalMonthId);
        setDaysInCalMonth(daysInCalMonth);
        setDaysInFisMonth(daysInFisMonth);
        setEndOfCalMonth(endOfCalMonth);
        setEndOfFisMonth(endOfFisMonth);
        setCalendarMonthName(calendarMonthName);
        setFiscalMonthName(fiscalMonthName);
        setCalendarQuarterDesc(calendarQuarterDesc);
        setCalendarQuarterId(calendarQuarterId);
        setFiscalQuarterDesc(fiscalQuarterDesc);
        setFiscalQuarterId(fiscalQuarterId);
        setDaysInCalQuarter(daysInCalQuarter);
        setDaysInFisQuarter(daysInFisQuarter);
        setEndOfCalQuarter(endOfCalQuarter);
        setEndOfFisQuarter(endOfFisQuarter);
        setCalendarQuarterNumber(calendarQuarterNumber);
        setFiscalQuarterNumber(fiscalQuarterNumber);
        setCalendarYear(calendarYear);
        setCalendarYearId(calendarYearId);
        setFiscalYear(fiscalYear);
        setFiscalYearId(fiscalYearId);
        setDaysInCalYear(daysInCalYear);
        setDaysInFisYear(daysInFisYear);
        setEndOfCalYear(endOfCalYear);
        setEndOfFisYear(endOfFisYear);
        resetTouchedOnNotNull();
    }
}
