/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Hr;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records.DepartmentsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Departments
        extends TableImpl<DepartmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR.DEPARTMENTS</code>
     */
    public static final Departments DEPARTMENTS = new Departments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepartmentsRecord> getRecordType() {
        return DepartmentsRecord.class;
    }

    /**
     * The column <code>HR.DEPARTMENTS.DEPARTMENT_ID</code>.
     */
    public final TableField<DepartmentsRecord, Long> DEPARTMENT_ID =
            createField(DSL.name("DEPARTMENT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>HR.DEPARTMENTS.DEPARTMENT_NAME</code>.
     */
    public final TableField<DepartmentsRecord, String> DEPARTMENT_NAME =
            createField(DSL.name("DEPARTMENT_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.DEPARTMENTS.MANAGER_ID</code>.
     */
    public final TableField<DepartmentsRecord, Long> MANAGER_ID =
            createField(DSL.name("MANAGER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>HR.DEPARTMENTS.LOCATION_ID</code>.
     */
    public final TableField<DepartmentsRecord, Long> LOCATION_ID =
            createField(DSL.name("LOCATION_ID"), SQLDataType.BIGINT, this, "");

    private Departments(Name alias, Table<DepartmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Departments(Name alias, Table<DepartmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>HR.DEPARTMENTS</code> table reference
     */
    public Departments(String alias) {
        this(DSL.name(alias), DEPARTMENTS);
    }

    /**
     * Create an aliased <code>HR.DEPARTMENTS</code> table reference
     */
    public Departments(Name alias) {
        this(alias, DEPARTMENTS);
    }

    /**
     * Create a <code>HR.DEPARTMENTS</code> table reference
     */
    public Departments() {
        this(DSL.name("DEPARTMENTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Hr.HR;
    }

    @Override
    public UniqueKey<DepartmentsRecord> getPrimaryKey() {
        return Keys.PK_DEPARTMENTS;
    }

    @Override
    public Departments as(String alias) {
        return new Departments(DSL.name(alias), this);
    }

    @Override
    public Departments as(Name alias) {
        return new Departments(alias, this);
    }

    @Override
    public Departments as(Table<?> alias) {
        return new Departments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Departments rename(String name) {
        return new Departments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Departments rename(Name name) {
        return new Departments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Departments rename(Table<?> name) {
        return new Departments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Departments where(Condition condition) {
        return new Departments(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Departments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Departments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Departments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Departments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Departments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Departments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Departments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Departments whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Departments whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
