/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Hr;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records.EmpDetailsViewRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmpDetailsView extends TableImpl<EmpDetailsViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR.EMP_DETAILS_VIEW</code>
     */
    public static final EmpDetailsView EMP_DETAILS_VIEW = new EmpDetailsView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmpDetailsViewRecord> getRecordType() {
        return EmpDetailsViewRecord.class;
    }

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.EMPLOYEE_ID</code>.
     */
    public final TableField<EmpDetailsViewRecord, Long> EMPLOYEE_ID = createField(DSL.name("EMPLOYEE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.JOB_ID</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> JOB_ID = createField(DSL.name("JOB_ID"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.MANAGER_ID</code>.
     */
    public final TableField<EmpDetailsViewRecord, Long> MANAGER_ID = createField(DSL.name("MANAGER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.DEPARTMENT_ID</code>.
     */
    public final TableField<EmpDetailsViewRecord, Long> DEPARTMENT_ID = createField(DSL.name("DEPARTMENT_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.LOCATION_ID</code>.
     */
    public final TableField<EmpDetailsViewRecord, Long> LOCATION_ID = createField(DSL.name("LOCATION_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.COUNTRY_ID</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> COUNTRY_ID = createField(DSL.name("COUNTRY_ID"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.FIRST_NAME</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> FIRST_NAME = createField(DSL.name("FIRST_NAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.LAST_NAME</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.SALARY</code>.
     */
    public final TableField<EmpDetailsViewRecord, BigDecimal> SALARY = createField(DSL.name("SALARY"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.COMMISSION_PCT</code>.
     */
    public final TableField<EmpDetailsViewRecord, BigDecimal> COMMISSION_PCT = createField(DSL.name("COMMISSION_PCT"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.DEPARTMENT_NAME</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> DEPARTMENT_NAME = createField(DSL.name("DEPARTMENT_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.JOB_TITLE</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> JOB_TITLE = createField(DSL.name("JOB_TITLE"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.CITY</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> CITY = createField(DSL.name("CITY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.STATE_PROVINCE</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> STATE_PROVINCE = createField(DSL.name("STATE_PROVINCE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.COUNTRY_NAME</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> COUNTRY_NAME = createField(DSL.name("COUNTRY_NAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>HR.EMP_DETAILS_VIEW.REGION_NAME</code>.
     */
    public final TableField<EmpDetailsViewRecord, String> REGION_NAME = createField(DSL.name("REGION_NAME"), SQLDataType.VARCHAR, this, "");

    private EmpDetailsView(Name alias, Table<EmpDetailsViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmpDetailsView(Name alias, Table<EmpDetailsViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view(), where);
    }

    /**
     * Create an aliased <code>HR.EMP_DETAILS_VIEW</code> table reference
     */
    public EmpDetailsView(String alias) {
        this(DSL.name(alias), EMP_DETAILS_VIEW);
    }

    /**
     * Create an aliased <code>HR.EMP_DETAILS_VIEW</code> table reference
     */
    public EmpDetailsView(Name alias) {
        this(alias, EMP_DETAILS_VIEW);
    }

    /**
     * Create a <code>HR.EMP_DETAILS_VIEW</code> table reference
     */
    public EmpDetailsView() {
        this(DSL.name("EMP_DETAILS_VIEW"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Hr.HR;
    }

    @Override
    public EmpDetailsView as(String alias) {
        return new EmpDetailsView(DSL.name(alias), this);
    }

    @Override
    public EmpDetailsView as(Name alias) {
        return new EmpDetailsView(alias, this);
    }

    @Override
    public EmpDetailsView as(Table<?> alias) {
        return new EmpDetailsView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmpDetailsView rename(String name) {
        return new EmpDetailsView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmpDetailsView rename(Name name) {
        return new EmpDetailsView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmpDetailsView rename(Table<?> name) {
        return new EmpDetailsView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmpDetailsView where(Condition condition) {
        return new EmpDetailsView(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmpDetailsView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmpDetailsView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmpDetailsView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmpDetailsView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmpDetailsView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmpDetailsView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmpDetailsView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmpDetailsView whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmpDetailsView whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
