/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Hr;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records.EmployeesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Employees
        extends TableImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR.EMPLOYEES</code>
     */
    public static final Employees EMPLOYEES = new Employees();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeesRecord> getRecordType() {
        return EmployeesRecord.class;
    }

    /**
     * The column <code>HR.EMPLOYEES.EMPLOYEE_ID</code>.
     */
    public final TableField<EmployeesRecord, Long> EMPLOYEE_ID =
            createField(DSL.name("EMPLOYEE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>HR.EMPLOYEES.FIRST_NAME</code>.
     */
    public final TableField<EmployeesRecord, String> FIRST_NAME =
            createField(DSL.name("FIRST_NAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>HR.EMPLOYEES.LAST_NAME</code>.
     */
    public final TableField<EmployeesRecord, String> LAST_NAME =
            createField(DSL.name("LAST_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMPLOYEES.EMAIL</code>.
     */
    public final TableField<EmployeesRecord, String> EMAIL =
            createField(DSL.name("EMAIL"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMPLOYEES.PHONE_NUMBER</code>.
     */
    public final TableField<EmployeesRecord, String> PHONE_NUMBER =
            createField(DSL.name("PHONE_NUMBER"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>HR.EMPLOYEES.HIRE_DATE</code>.
     */
    public final TableField<EmployeesRecord, LocalDateTime> HIRE_DATE =
            createField(DSL.name("HIRE_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>HR.EMPLOYEES.JOB_ID</code>.
     */
    public final TableField<EmployeesRecord, String> JOB_ID =
            createField(DSL.name("JOB_ID"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.EMPLOYEES.SALARY</code>.
     */
    public final TableField<EmployeesRecord, BigDecimal> SALARY =
            createField(DSL.name("SALARY"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>HR.EMPLOYEES.COMMISSION_PCT</code>.
     */
    public final TableField<EmployeesRecord, BigDecimal> COMMISSION_PCT =
            createField(DSL.name("COMMISSION_PCT"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>HR.EMPLOYEES.MANAGER_ID</code>.
     */
    public final TableField<EmployeesRecord, Long> MANAGER_ID =
            createField(DSL.name("MANAGER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>HR.EMPLOYEES.DEPARTMENT_ID</code>.
     */
    public final TableField<EmployeesRecord, Long> DEPARTMENT_ID =
            createField(DSL.name("DEPARTMENT_ID"), SQLDataType.BIGINT, this, "");

    private Employees(Name alias, Table<EmployeesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Employees(Name alias, Table<EmployeesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>HR.EMPLOYEES</code> table reference
     */
    public Employees(String alias) {
        this(DSL.name(alias), EMPLOYEES);
    }

    /**
     * Create an aliased <code>HR.EMPLOYEES</code> table reference
     */
    public Employees(Name alias) {
        this(alias, EMPLOYEES);
    }

    /**
     * Create a <code>HR.EMPLOYEES</code> table reference
     */
    public Employees() {
        this(DSL.name("EMPLOYEES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Hr.HR;
    }

    @Override
    public UniqueKey<EmployeesRecord> getPrimaryKey() {
        return Keys.PK_EMPLOYEES;
    }

    @Override
    public Employees as(String alias) {
        return new Employees(DSL.name(alias), this);
    }

    @Override
    public Employees as(Name alias) {
        return new Employees(alias, this);
    }

    @Override
    public Employees as(Table<?> alias) {
        return new Employees(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(String name) {
        return new Employees(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Name name) {
        return new Employees(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Table<?> name) {
        return new Employees(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition condition) {
        return new Employees(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
