/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Hr;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records.JobHistoryRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JobHistory
        extends TableImpl<JobHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR.JOB_HISTORY</code>
     */
    public static final JobHistory JOB_HISTORY = new JobHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobHistoryRecord> getRecordType() {
        return JobHistoryRecord.class;
    }

    /**
     * The column <code>HR.JOB_HISTORY.EMPLOYEE_ID</code>.
     */
    public final TableField<JobHistoryRecord, Long> EMPLOYEE_ID =
            createField(DSL.name("EMPLOYEE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>HR.JOB_HISTORY.START_DATE</code>.
     */
    public final TableField<JobHistoryRecord, LocalDateTime> START_DATE =
            createField(DSL.name("START_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>HR.JOB_HISTORY.END_DATE</code>.
     */
    public final TableField<JobHistoryRecord, LocalDateTime> END_DATE =
            createField(DSL.name("END_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>HR.JOB_HISTORY.JOB_ID</code>.
     */
    public final TableField<JobHistoryRecord, String> JOB_ID =
            createField(DSL.name("JOB_ID"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.JOB_HISTORY.DEPARTMENT_ID</code>.
     */
    public final TableField<JobHistoryRecord, Long> DEPARTMENT_ID =
            createField(DSL.name("DEPARTMENT_ID"), SQLDataType.BIGINT, this, "");

    private JobHistory(Name alias, Table<JobHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JobHistory(Name alias, Table<JobHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>HR.JOB_HISTORY</code> table reference
     */
    public JobHistory(String alias) {
        this(DSL.name(alias), JOB_HISTORY);
    }

    /**
     * Create an aliased <code>HR.JOB_HISTORY</code> table reference
     */
    public JobHistory(Name alias) {
        this(alias, JOB_HISTORY);
    }

    /**
     * Create a <code>HR.JOB_HISTORY</code> table reference
     */
    public JobHistory() {
        this(DSL.name("JOB_HISTORY"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Hr.HR;
    }

    @Override
    public UniqueKey<JobHistoryRecord> getPrimaryKey() {
        return Keys.PK_JOB_HISTORY;
    }

    @Override
    public JobHistory as(String alias) {
        return new JobHistory(DSL.name(alias), this);
    }

    @Override
    public JobHistory as(Name alias) {
        return new JobHistory(alias, this);
    }

    @Override
    public JobHistory as(Table<?> alias) {
        return new JobHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JobHistory rename(String name) {
        return new JobHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobHistory rename(Name name) {
        return new JobHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobHistory rename(Table<?> name) {
        return new JobHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobHistory where(Condition condition) {
        return new JobHistory(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobHistory whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobHistory whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
