/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Hr;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records.JobsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Jobs
        extends TableImpl<JobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR.JOBS</code>
     */
    public static final Jobs JOBS = new Jobs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobsRecord> getRecordType() {
        return JobsRecord.class;
    }

    /**
     * The column <code>HR.JOBS.JOB_ID</code>.
     */
    public final TableField<JobsRecord, String> JOB_ID =
            createField(DSL.name("JOB_ID"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.JOBS.JOB_TITLE</code>.
     */
    public final TableField<JobsRecord, String> JOB_TITLE =
            createField(DSL.name("JOB_TITLE"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>HR.JOBS.MIN_SALARY</code>.
     */
    public final TableField<JobsRecord, BigDecimal> MIN_SALARY =
            createField(DSL.name("MIN_SALARY"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>HR.JOBS.MAX_SALARY</code>.
     */
    public final TableField<JobsRecord, BigDecimal> MAX_SALARY =
            createField(DSL.name("MAX_SALARY"), SQLDataType.NUMERIC, this, "");

    private Jobs(Name alias, Table<JobsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Jobs(Name alias, Table<JobsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>HR.JOBS</code> table reference
     */
    public Jobs(String alias) {
        this(DSL.name(alias), JOBS);
    }

    /**
     * Create an aliased <code>HR.JOBS</code> table reference
     */
    public Jobs(Name alias) {
        this(alias, JOBS);
    }

    /**
     * Create a <code>HR.JOBS</code> table reference
     */
    public Jobs() {
        this(DSL.name("JOBS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Hr.HR;
    }

    @Override
    public UniqueKey<JobsRecord> getPrimaryKey() {
        return Keys.PK_JOBS;
    }

    @Override
    public Jobs as(String alias) {
        return new Jobs(DSL.name(alias), this);
    }

    @Override
    public Jobs as(Name alias) {
        return new Jobs(alias, this);
    }

    @Override
    public Jobs as(Table<?> alias) {
        return new Jobs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(String name) {
        return new Jobs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(Name name) {
        return new Jobs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(Table<?> name) {
        return new Jobs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Condition condition) {
        return new Jobs(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
