/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Hr;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records.RegionsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Regions extends TableImpl<RegionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR.REGIONS</code>
     */
    public static final Regions REGIONS = new Regions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RegionsRecord> getRecordType() {
        return RegionsRecord.class;
    }

    /**
     * The column <code>HR.REGIONS.REGION_ID</code>.
     */
    public final TableField<RegionsRecord, Long> REGION_ID = createField(DSL.name("REGION_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>HR.REGIONS.REGION_NAME</code>.
     */
    public final TableField<RegionsRecord, String> REGION_NAME = createField(DSL.name("REGION_NAME"), SQLDataType.VARCHAR, this, "");

    private Regions(Name alias, Table<RegionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Regions(Name alias, Table<RegionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>HR.REGIONS</code> table reference
     */
    public Regions(String alias) {
        this(DSL.name(alias), REGIONS);
    }

    /**
     * Create an aliased <code>HR.REGIONS</code> table reference
     */
    public Regions(Name alias) {
        this(alias, REGIONS);
    }

    /**
     * Create a <code>HR.REGIONS</code> table reference
     */
    public Regions() {
        this(DSL.name("REGIONS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Hr.HR;
    }

    @Override
    public UniqueKey<RegionsRecord> getPrimaryKey() {
        return Keys.PK_REGIONS;
    }

    @Override
    public Regions as(String alias) {
        return new Regions(DSL.name(alias), this);
    }

    @Override
    public Regions as(Name alias) {
        return new Regions(alias, this);
    }

    @Override
    public Regions as(Table<?> alias) {
        return new Regions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Regions rename(String name) {
        return new Regions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Regions rename(Name name) {
        return new Regions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Regions rename(Table<?> name) {
        return new Regions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Regions where(Condition condition) {
        return new Regions(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Regions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Regions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Regions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Regions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Regions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Regions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Regions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Regions whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Regions whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
