/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.CustomerOrderProductsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CustomerOrderProducts
        extends TableImpl<CustomerOrderProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.CUSTOMER_ORDER_PRODUCTS</code>
     */
    public static final CustomerOrderProducts CUSTOMER_ORDER_PRODUCTS = new CustomerOrderProducts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerOrderProductsRecord> getRecordType() {
        return CustomerOrderProductsRecord.class;
    }

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_ID</code>.
     */
    public final TableField<CustomerOrderProductsRecord, Long> ORDER_ID =
            createField(DSL.name("ORDER_ID"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this,
                        "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_TMS</code>.
     */
    public final TableField<CustomerOrderProductsRecord, LocalDateTime> ORDER_TMS =
            createField(DSL.name("ORDER_TMS"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_STATUS</code>.
     */
    public final TableField<CustomerOrderProductsRecord, String> ORDER_STATUS =
            createField(DSL.name("ORDER_STATUS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.CUSTOMER_ID</code>.
     */
    public final TableField<CustomerOrderProductsRecord, Long> CUSTOMER_ID =
            createField(DSL.name("CUSTOMER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.EMAIL_ADDRESS</code>.
     */
    public final TableField<CustomerOrderProductsRecord, String> EMAIL_ADDRESS =
            createField(DSL.name("EMAIL_ADDRESS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.FULL_NAME</code>.
     */
    public final TableField<CustomerOrderProductsRecord, String> FULL_NAME =
            createField(DSL.name("FULL_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_TOTAL</code>.
     */
    public final TableField<CustomerOrderProductsRecord, BigDecimal> ORDER_TOTAL =
            createField(DSL.name("ORDER_TOTAL"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.CUSTOMER_ORDER_PRODUCTS.ITEMS</code>.
     */
    public final TableField<CustomerOrderProductsRecord, String> ITEMS =
            createField(DSL.name("ITEMS"), SQLDataType.VARCHAR, this, "");

    private CustomerOrderProducts(Name alias, Table<CustomerOrderProductsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerOrderProducts(Name alias, Table<CustomerOrderProductsRecord> aliased, Field<?>[] parameters,
                                  Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view(), where);
    }

    /**
     * Create an aliased <code>CO.CUSTOMER_ORDER_PRODUCTS</code> table reference
     */
    public CustomerOrderProducts(String alias) {
        this(DSL.name(alias), CUSTOMER_ORDER_PRODUCTS);
    }

    /**
     * Create an aliased <code>CO.CUSTOMER_ORDER_PRODUCTS</code> table reference
     */
    public CustomerOrderProducts(Name alias) {
        this(alias, CUSTOMER_ORDER_PRODUCTS);
    }

    /**
     * Create a <code>CO.CUSTOMER_ORDER_PRODUCTS</code> table reference
     */
    public CustomerOrderProducts() {
        this(DSL.name("CUSTOMER_ORDER_PRODUCTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public Identity<CustomerOrderProductsRecord, Long> getIdentity() {
        return (Identity<CustomerOrderProductsRecord, Long>) super.getIdentity();
    }

    @Override
    public CustomerOrderProducts as(String alias) {
        return new CustomerOrderProducts(DSL.name(alias), this);
    }

    @Override
    public CustomerOrderProducts as(Name alias) {
        return new CustomerOrderProducts(alias, this);
    }

    @Override
    public CustomerOrderProducts as(Table<?> alias) {
        return new CustomerOrderProducts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerOrderProducts rename(String name) {
        return new CustomerOrderProducts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerOrderProducts rename(Name name) {
        return new CustomerOrderProducts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerOrderProducts rename(Table<?> name) {
        return new CustomerOrderProducts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerOrderProducts where(Condition condition) {
        return new CustomerOrderProducts(getQualifiedName(), aliased() ? this : null, null,
                                         Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerOrderProducts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerOrderProducts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerOrderProducts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerOrderProducts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerOrderProducts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerOrderProducts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerOrderProducts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerOrderProducts whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerOrderProducts whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
