/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.OrderItemsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class OrderItems
        extends TableImpl<OrderItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.ORDER_ITEMS</code>
     */
    public static final OrderItems ORDER_ITEMS = new OrderItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderItemsRecord> getRecordType() {
        return OrderItemsRecord.class;
    }

    /**
     * The column <code>CO.ORDER_ITEMS.ORDER_ID</code>.
     */
    public final TableField<OrderItemsRecord, Long> ORDER_ID =
            createField(DSL.name("ORDER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CO.ORDER_ITEMS.LINE_ITEM_ID</code>.
     */
    public final TableField<OrderItemsRecord, Long> LINE_ITEM_ID =
            createField(DSL.name("LINE_ITEM_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CO.ORDER_ITEMS.PRODUCT_ID</code>.
     */
    public final TableField<OrderItemsRecord, Long> PRODUCT_ID =
            createField(DSL.name("PRODUCT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CO.ORDER_ITEMS.UNIT_PRICE</code>.
     */
    public final TableField<OrderItemsRecord, BigDecimal> UNIT_PRICE =
            createField(DSL.name("UNIT_PRICE"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>CO.ORDER_ITEMS.QUANTITY</code>.
     */
    public final TableField<OrderItemsRecord, BigDecimal> QUANTITY =
            createField(DSL.name("QUANTITY"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>CO.ORDER_ITEMS.SHIPMENT_ID</code>.
     */
    public final TableField<OrderItemsRecord, Long> SHIPMENT_ID =
            createField(DSL.name("SHIPMENT_ID"), SQLDataType.BIGINT, this, "");

    private OrderItems(Name alias, Table<OrderItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrderItems(Name alias, Table<OrderItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CO.ORDER_ITEMS</code> table reference
     */
    public OrderItems(String alias) {
        this(DSL.name(alias), ORDER_ITEMS);
    }

    /**
     * Create an aliased <code>CO.ORDER_ITEMS</code> table reference
     */
    public OrderItems(Name alias) {
        this(alias, ORDER_ITEMS);
    }

    /**
     * Create a <code>CO.ORDER_ITEMS</code> table reference
     */
    public OrderItems() {
        this(DSL.name("ORDER_ITEMS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public UniqueKey<OrderItemsRecord> getPrimaryKey() {
        return Keys.PK_ORDER_ITEMS;
    }

    @Override
    public OrderItems as(String alias) {
        return new OrderItems(DSL.name(alias), this);
    }

    @Override
    public OrderItems as(Name alias) {
        return new OrderItems(alias, this);
    }

    @Override
    public OrderItems as(Table<?> alias) {
        return new OrderItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItems rename(String name) {
        return new OrderItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItems rename(Name name) {
        return new OrderItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItems rename(Table<?> name) {
        return new OrderItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Condition condition) {
        return new OrderItems(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItems whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
