/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.ProductsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Products
        extends TableImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.PRODUCTS</code>
     */
    public static final Products PRODUCTS = new Products();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductsRecord> getRecordType() {
        return ProductsRecord.class;
    }

    /**
     * The column <code>CO.PRODUCTS.PRODUCT_ID</code>.
     */
    public final TableField<ProductsRecord, Long> PRODUCT_ID =
            createField(DSL.name("PRODUCT_ID"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this,
                        "");

    /**
     * The column <code>CO.PRODUCTS.PRODUCT_NAME</code>.
     */
    public final TableField<ProductsRecord, String> PRODUCT_NAME =
            createField(DSL.name("PRODUCT_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.PRODUCTS.UNIT_PRICE</code>.
     */
    public final TableField<ProductsRecord, BigDecimal> UNIT_PRICE =
            createField(DSL.name("UNIT_PRICE"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.PRODUCTS.PRODUCT_DETAILS</code>.
     */
    public final TableField<ProductsRecord, byte[]> PRODUCT_DETAILS =
            createField(DSL.name("PRODUCT_DETAILS"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>CO.PRODUCTS.PRODUCT_IMAGE</code>.
     */
    public final TableField<ProductsRecord, byte[]> PRODUCT_IMAGE =
            createField(DSL.name("PRODUCT_IMAGE"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>CO.PRODUCTS.IMAGE_MIME_TYPE</code>.
     */
    public final TableField<ProductsRecord, String> IMAGE_MIME_TYPE =
            createField(DSL.name("IMAGE_MIME_TYPE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.PRODUCTS.IMAGE_FILENAME</code>.
     */
    public final TableField<ProductsRecord, String> IMAGE_FILENAME =
            createField(DSL.name("IMAGE_FILENAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.PRODUCTS.IMAGE_CHARSET</code>.
     */
    public final TableField<ProductsRecord, String> IMAGE_CHARSET =
            createField(DSL.name("IMAGE_CHARSET"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.PRODUCTS.IMAGE_LAST_UPDATED</code>.
     */
    public final TableField<ProductsRecord, LocalDateTime> IMAGE_LAST_UPDATED =
            createField(DSL.name("IMAGE_LAST_UPDATED"), SQLDataType.LOCALDATETIME(0), this, "");

    private Products(Name alias, Table<ProductsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Products(Name alias, Table<ProductsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CO.PRODUCTS</code> table reference
     */
    public Products(String alias) {
        this(DSL.name(alias), PRODUCTS);
    }

    /**
     * Create an aliased <code>CO.PRODUCTS</code> table reference
     */
    public Products(Name alias) {
        this(alias, PRODUCTS);
    }

    /**
     * Create a <code>CO.PRODUCTS</code> table reference
     */
    public Products() {
        this(DSL.name("PRODUCTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public Identity<ProductsRecord, Long> getIdentity() {
        return (Identity<ProductsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductsRecord> getPrimaryKey() {
        return Keys.PK_PRODUCTS;
    }

    @Override
    public Products as(String alias) {
        return new Products(DSL.name(alias), this);
    }

    @Override
    public Products as(Name alias) {
        return new Products(alias, this);
    }

    @Override
    public Products as(Table<?> alias) {
        return new Products(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(String name) {
        return new Products(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Name name) {
        return new Products(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Table<?> name) {
        return new Products(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Condition condition) {
        return new Products(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
