/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.ProductReviewsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProductReviews
        extends TableImpl<ProductReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.PRODUCT_REVIEWS</code>
     */
    public static final ProductReviews PRODUCT_REVIEWS = new ProductReviews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductReviewsRecord> getRecordType() {
        return ProductReviewsRecord.class;
    }

    /**
     * The column <code>CO.PRODUCT_REVIEWS.PRODUCT_NAME</code>.
     */
    public final TableField<ProductReviewsRecord, String> PRODUCT_NAME =
            createField(DSL.name("PRODUCT_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.PRODUCT_REVIEWS.RATING</code>.
     */
    public final TableField<ProductReviewsRecord, BigDecimal> RATING =
            createField(DSL.name("RATING"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.PRODUCT_REVIEWS.AVG_RATING</code>.
     */
    public final TableField<ProductReviewsRecord, BigDecimal> AVG_RATING =
            createField(DSL.name("AVG_RATING"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.PRODUCT_REVIEWS.REVIEW</code>.
     */
    public final TableField<ProductReviewsRecord, String> REVIEW =
            createField(DSL.name("REVIEW"), SQLDataType.VARCHAR, this, "");

    private ProductReviews(Name alias, Table<ProductReviewsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProductReviews(Name alias, Table<ProductReviewsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view(), where);
    }

    /**
     * Create an aliased <code>CO.PRODUCT_REVIEWS</code> table reference
     */
    public ProductReviews(String alias) {
        this(DSL.name(alias), PRODUCT_REVIEWS);
    }

    /**
     * Create an aliased <code>CO.PRODUCT_REVIEWS</code> table reference
     */
    public ProductReviews(Name alias) {
        this(alias, PRODUCT_REVIEWS);
    }

    /**
     * Create a <code>CO.PRODUCT_REVIEWS</code> table reference
     */
    public ProductReviews() {
        this(DSL.name("PRODUCT_REVIEWS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public ProductReviews as(String alias) {
        return new ProductReviews(DSL.name(alias), this);
    }

    @Override
    public ProductReviews as(Name alias) {
        return new ProductReviews(alias, this);
    }

    @Override
    public ProductReviews as(Table<?> alias) {
        return new ProductReviews(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductReviews rename(String name) {
        return new ProductReviews(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductReviews rename(Name name) {
        return new ProductReviews(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductReviews rename(Table<?> name) {
        return new ProductReviews(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Condition condition) {
        return new ProductReviews(getQualifiedName(), aliased() ? this : null, null,
                                  Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
