/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.ProductOrdersRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProductOrders
        extends TableImpl<ProductOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.PRODUCT_ORDERS</code>
     */
    public static final ProductOrders PRODUCT_ORDERS = new ProductOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductOrdersRecord> getRecordType() {
        return ProductOrdersRecord.class;
    }

    /**
     * The column <code>CO.PRODUCT_ORDERS.PRODUCT_NAME</code>.
     */
    public final TableField<ProductOrdersRecord, String> PRODUCT_NAME =
            createField(DSL.name("PRODUCT_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.PRODUCT_ORDERS.ORDER_STATUS</code>.
     */
    public final TableField<ProductOrdersRecord, String> ORDER_STATUS =
            createField(DSL.name("ORDER_STATUS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.PRODUCT_ORDERS.TOTAL_SALES</code>.
     */
    public final TableField<ProductOrdersRecord, BigDecimal> TOTAL_SALES =
            createField(DSL.name("TOTAL_SALES"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.PRODUCT_ORDERS.ORDER_COUNT</code>.
     */
    public final TableField<ProductOrdersRecord, BigDecimal> ORDER_COUNT =
            createField(DSL.name("ORDER_COUNT"), SQLDataType.NUMERIC, this, "");

    private ProductOrders(Name alias, Table<ProductOrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProductOrders(Name alias, Table<ProductOrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view(), where);
    }

    /**
     * Create an aliased <code>CO.PRODUCT_ORDERS</code> table reference
     */
    public ProductOrders(String alias) {
        this(DSL.name(alias), PRODUCT_ORDERS);
    }

    /**
     * Create an aliased <code>CO.PRODUCT_ORDERS</code> table reference
     */
    public ProductOrders(Name alias) {
        this(alias, PRODUCT_ORDERS);
    }

    /**
     * Create a <code>CO.PRODUCT_ORDERS</code> table reference
     */
    public ProductOrders() {
        this(DSL.name("PRODUCT_ORDERS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public ProductOrders as(String alias) {
        return new ProductOrders(DSL.name(alias), this);
    }

    @Override
    public ProductOrders as(Name alias) {
        return new ProductOrders(alias, this);
    }

    @Override
    public ProductOrders as(Table<?> alias) {
        return new ProductOrders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductOrders rename(String name) {
        return new ProductOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductOrders rename(Name name) {
        return new ProductOrders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductOrders rename(Table<?> name) {
        return new ProductOrders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOrders where(Condition condition) {
        return new ProductOrders(getQualifiedName(), aliased() ? this : null, null,
                                 Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOrders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOrders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOrders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOrders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOrders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOrders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOrders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOrders whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOrders whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
