/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.ShipmentsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Shipments
        extends TableImpl<ShipmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.SHIPMENTS</code>
     */
    public static final Shipments SHIPMENTS = new Shipments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShipmentsRecord> getRecordType() {
        return ShipmentsRecord.class;
    }

    /**
     * The column <code>CO.SHIPMENTS.SHIPMENT_ID</code>.
     */
    public final TableField<ShipmentsRecord, Long> SHIPMENT_ID =
            createField(DSL.name("SHIPMENT_ID"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(),
                        this, "");

    /**
     * The column <code>CO.SHIPMENTS.STORE_ID</code>.
     */
    public final TableField<ShipmentsRecord, Long> STORE_ID =
            createField(DSL.name("STORE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CO.SHIPMENTS.CUSTOMER_ID</code>.
     */
    public final TableField<ShipmentsRecord, Long> CUSTOMER_ID =
            createField(DSL.name("CUSTOMER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CO.SHIPMENTS.DELIVERY_ADDRESS</code>.
     */
    public final TableField<ShipmentsRecord, String> DELIVERY_ADDRESS =
            createField(DSL.name("DELIVERY_ADDRESS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.SHIPMENTS.SHIPMENT_STATUS</code>.
     */
    public final TableField<ShipmentsRecord, String> SHIPMENT_STATUS =
            createField(DSL.name("SHIPMENT_STATUS"), SQLDataType.VARCHAR.nullable(false), this, "");

    private Shipments(Name alias, Table<ShipmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Shipments(Name alias, Table<ShipmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CO.SHIPMENTS</code> table reference
     */
    public Shipments(String alias) {
        this(DSL.name(alias), SHIPMENTS);
    }

    /**
     * Create an aliased <code>CO.SHIPMENTS</code> table reference
     */
    public Shipments(Name alias) {
        this(alias, SHIPMENTS);
    }

    /**
     * Create a <code>CO.SHIPMENTS</code> table reference
     */
    public Shipments() {
        this(DSL.name("SHIPMENTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public Identity<ShipmentsRecord, Long> getIdentity() {
        return (Identity<ShipmentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShipmentsRecord> getPrimaryKey() {
        return Keys.PK_SHIPMENTS;
    }

    @Override
    public Shipments as(String alias) {
        return new Shipments(DSL.name(alias), this);
    }

    @Override
    public Shipments as(Name alias) {
        return new Shipments(alias, this);
    }

    @Override
    public Shipments as(Table<?> alias) {
        return new Shipments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Shipments rename(String name) {
        return new Shipments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shipments rename(Name name) {
        return new Shipments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shipments rename(Table<?> name) {
        return new Shipments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shipments where(Condition condition) {
        return new Shipments(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shipments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shipments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shipments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shipments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shipments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shipments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shipments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shipments whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shipments whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
