/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.StoreOrdersRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StoreOrders
        extends TableImpl<StoreOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.STORE_ORDERS</code>
     */
    public static final StoreOrders STORE_ORDERS = new StoreOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreOrdersRecord> getRecordType() {
        return StoreOrdersRecord.class;
    }

    /**
     * The column <code>CO.STORE_ORDERS.TOTAL</code>.
     */
    public final TableField<StoreOrdersRecord, String> TOTAL =
            createField(DSL.name("TOTAL"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORE_ORDERS.STORE_NAME</code>.
     */
    public final TableField<StoreOrdersRecord, String> STORE_NAME =
            createField(DSL.name("STORE_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.STORE_ORDERS.ADDRESS</code>.
     */
    public final TableField<StoreOrdersRecord, String> ADDRESS =
            createField(DSL.name("ADDRESS"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORE_ORDERS.LATITUDE</code>.
     */
    public final TableField<StoreOrdersRecord, BigDecimal> LATITUDE =
            createField(DSL.name("LATITUDE"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.STORE_ORDERS.LONGITUDE</code>.
     */
    public final TableField<StoreOrdersRecord, BigDecimal> LONGITUDE =
            createField(DSL.name("LONGITUDE"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.STORE_ORDERS.ORDER_STATUS</code>.
     */
    public final TableField<StoreOrdersRecord, String> ORDER_STATUS =
            createField(DSL.name("ORDER_STATUS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.STORE_ORDERS.ORDER_COUNT</code>.
     */
    public final TableField<StoreOrdersRecord, BigDecimal> ORDER_COUNT =
            createField(DSL.name("ORDER_COUNT"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.STORE_ORDERS.TOTAL_SALES</code>.
     */
    public final TableField<StoreOrdersRecord, BigDecimal> TOTAL_SALES =
            createField(DSL.name("TOTAL_SALES"), SQLDataType.NUMERIC, this, "");

    private StoreOrders(Name alias, Table<StoreOrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StoreOrders(Name alias, Table<StoreOrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view(), where);
    }

    /**
     * Create an aliased <code>CO.STORE_ORDERS</code> table reference
     */
    public StoreOrders(String alias) {
        this(DSL.name(alias), STORE_ORDERS);
    }

    /**
     * Create an aliased <code>CO.STORE_ORDERS</code> table reference
     */
    public StoreOrders(Name alias) {
        this(alias, STORE_ORDERS);
    }

    /**
     * Create a <code>CO.STORE_ORDERS</code> table reference
     */
    public StoreOrders() {
        this(DSL.name("STORE_ORDERS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public StoreOrders as(String alias) {
        return new StoreOrders(DSL.name(alias), this);
    }

    @Override
    public StoreOrders as(Name alias) {
        return new StoreOrders(alias, this);
    }

    @Override
    public StoreOrders as(Table<?> alias) {
        return new StoreOrders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreOrders rename(String name) {
        return new StoreOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreOrders rename(Name name) {
        return new StoreOrders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreOrders rename(Table<?> name) {
        return new StoreOrders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreOrders where(Condition condition) {
        return new StoreOrders(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreOrders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreOrders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreOrders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreOrders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreOrders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreOrders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreOrders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreOrders whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreOrders whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
