/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Co;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.StoresRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Stores
        extends TableImpl<StoresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO.STORES</code>
     */
    public static final Stores STORES = new Stores();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoresRecord> getRecordType() {
        return StoresRecord.class;
    }

    /**
     * The column <code>CO.STORES.STORE_ID</code>.
     */
    public final TableField<StoresRecord, Long> STORE_ID =
            createField(DSL.name("STORE_ID"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this,
                        "");

    /**
     * The column <code>CO.STORES.STORE_NAME</code>.
     */
    public final TableField<StoresRecord, String> STORE_NAME =
            createField(DSL.name("STORE_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>CO.STORES.WEB_ADDRESS</code>.
     */
    public final TableField<StoresRecord, String> WEB_ADDRESS =
            createField(DSL.name("WEB_ADDRESS"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORES.PHYSICAL_ADDRESS</code>.
     */
    public final TableField<StoresRecord, String> PHYSICAL_ADDRESS =
            createField(DSL.name("PHYSICAL_ADDRESS"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORES.LATITUDE</code>.
     */
    public final TableField<StoresRecord, BigDecimal> LATITUDE =
            createField(DSL.name("LATITUDE"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.STORES.LONGITUDE</code>.
     */
    public final TableField<StoresRecord, BigDecimal> LONGITUDE =
            createField(DSL.name("LONGITUDE"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>CO.STORES.LOGO</code>.
     */
    public final TableField<StoresRecord, byte[]> LOGO = createField(DSL.name("LOGO"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>CO.STORES.LOGO_MIME_TYPE</code>.
     */
    public final TableField<StoresRecord, String> LOGO_MIME_TYPE =
            createField(DSL.name("LOGO_MIME_TYPE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORES.LOGO_FILENAME</code>.
     */
    public final TableField<StoresRecord, String> LOGO_FILENAME =
            createField(DSL.name("LOGO_FILENAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORES.LOGO_CHARSET</code>.
     */
    public final TableField<StoresRecord, String> LOGO_CHARSET =
            createField(DSL.name("LOGO_CHARSET"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>CO.STORES.LOGO_LAST_UPDATED</code>.
     */
    public final TableField<StoresRecord, LocalDateTime> LOGO_LAST_UPDATED =
            createField(DSL.name("LOGO_LAST_UPDATED"), SQLDataType.LOCALDATETIME(0), this, "");

    private Stores(Name alias, Table<StoresRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Stores(Name alias, Table<StoresRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CO.STORES</code> table reference
     */
    public Stores(String alias) {
        this(DSL.name(alias), STORES);
    }

    /**
     * Create an aliased <code>CO.STORES</code> table reference
     */
    public Stores(Name alias) {
        this(alias, STORES);
    }

    /**
     * Create a <code>CO.STORES</code> table reference
     */
    public Stores() {
        this(DSL.name("STORES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Co.CO;
    }

    @Override
    public Identity<StoresRecord, Long> getIdentity() {
        return (Identity<StoresRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoresRecord> getPrimaryKey() {
        return Keys.PK_STORES;
    }

    @Override
    public Stores as(String alias) {
        return new Stores(DSL.name(alias), this);
    }

    @Override
    public Stores as(Name alias) {
        return new Stores(alias, this);
    }

    @Override
    public Stores as(Table<?> alias) {
        return new Stores(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stores rename(String name) {
        return new Stores(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stores rename(Name name) {
        return new Stores(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stores rename(Table<?> name) {
        return new Stores(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Condition condition) {
        return new Stores(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
