/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Countries;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CountriesRecord
        extends UpdatableRecordImpl<CountriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.COUNTRIES.COUNTRY_ID</code>.
     */
    public void setCountryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.COUNTRIES.COUNTRY_ID</code>.
     */
    public String getCountryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>HR.COUNTRIES.COUNTRY_NAME</code>.
     */
    public void setCountryName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.COUNTRIES.COUNTRY_NAME</code>.
     */
    public String getCountryName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>HR.COUNTRIES.REGION_ID</code>.
     */
    public void setRegionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.COUNTRIES.REGION_ID</code>.
     */
    public Long getRegionId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountriesRecord
     */
    public CountriesRecord() {
        super(Countries.COUNTRIES);
    }

    /**
     * Create a detached, initialised CountriesRecord
     */
    public CountriesRecord(String countryId, String countryName, Long regionId) {
        super(Countries.COUNTRIES);

        setCountryId(countryId);
        setCountryName(countryName);
        setRegionId(regionId);
        resetTouchedOnNotNull();
    }
}
