/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Departments;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DepartmentsRecord extends UpdatableRecordImpl<DepartmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.DEPARTMENTS.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.DEPARTMENTS.DEPARTMENT_ID</code>.
     */
    public Long getDepartmentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>HR.DEPARTMENTS.DEPARTMENT_NAME</code>.
     */
    public void setDepartmentName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.DEPARTMENTS.DEPARTMENT_NAME</code>.
     */
    public String getDepartmentName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>HR.DEPARTMENTS.MANAGER_ID</code>.
     */
    public void setManagerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.DEPARTMENTS.MANAGER_ID</code>.
     */
    public Long getManagerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>HR.DEPARTMENTS.LOCATION_ID</code>.
     */
    public void setLocationId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>HR.DEPARTMENTS.LOCATION_ID</code>.
     */
    public Long getLocationId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DepartmentsRecord
     */
    public DepartmentsRecord() {
        super(Departments.DEPARTMENTS);
    }

    /**
     * Create a detached, initialised DepartmentsRecord
     */
    public DepartmentsRecord(Long departmentId, String departmentName, Long managerId, Long locationId) {
        super(Departments.DEPARTMENTS);

        setDepartmentId(departmentId);
        setDepartmentName(departmentName);
        setManagerId(managerId);
        setLocationId(locationId);
        resetTouchedOnNotNull();
    }
}
