/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.EmpDetailsView;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EmpDetailsViewRecord
        extends TableRecordImpl<EmpDetailsViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.EMPLOYEE_ID</code>.
     */
    public void setEmployeeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.EMPLOYEE_ID</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.JOB_ID</code>.
     */
    public void setJobId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.JOB_ID</code>.
     */
    public String getJobId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.MANAGER_ID</code>.
     */
    public void setManagerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.MANAGER_ID</code>.
     */
    public Long getManagerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.DEPARTMENT_ID</code>.
     */
    public Long getDepartmentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.LOCATION_ID</code>.
     */
    public void setLocationId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.LOCATION_ID</code>.
     */
    public Long getLocationId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.COUNTRY_ID</code>.
     */
    public void setCountryId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.COUNTRY_ID</code>.
     */
    public String getCountryId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.SALARY</code>.
     */
    public void setSalary(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.SALARY</code>.
     */
    public BigDecimal getSalary() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.COMMISSION_PCT</code>.
     */
    public void setCommissionPct(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.COMMISSION_PCT</code>.
     */
    public BigDecimal getCommissionPct() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.DEPARTMENT_NAME</code>.
     */
    public void setDepartmentName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.DEPARTMENT_NAME</code>.
     */
    public String getDepartmentName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.JOB_TITLE</code>.
     */
    public void setJobTitle(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.JOB_TITLE</code>.
     */
    public String getJobTitle() {
        return (String) get(11);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.CITY</code>.
     */
    public void setCity(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.CITY</code>.
     */
    public String getCity() {
        return (String) get(12);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.STATE_PROVINCE</code>.
     */
    public void setStateProvince(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.STATE_PROVINCE</code>.
     */
    public String getStateProvince() {
        return (String) get(13);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.COUNTRY_NAME</code>.
     */
    public void setCountryName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.COUNTRY_NAME</code>.
     */
    public String getCountryName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>HR.EMP_DETAILS_VIEW.REGION_NAME</code>.
     */
    public void setRegionName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>HR.EMP_DETAILS_VIEW.REGION_NAME</code>.
     */
    public String getRegionName() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmpDetailsViewRecord
     */
    public EmpDetailsViewRecord() {
        super(EmpDetailsView.EMP_DETAILS_VIEW);
    }

    /**
     * Create a detached, initialised EmpDetailsViewRecord
     */
    public EmpDetailsViewRecord(Long employeeId, String jobId, Long managerId, Long departmentId, Long locationId,
                                String countryId, String firstName, String lastName, BigDecimal salary,
                                BigDecimal commissionPct, String departmentName, String jobTitle, String city,
                                String stateProvince, String countryName, String regionName) {
        super(EmpDetailsView.EMP_DETAILS_VIEW);

        setEmployeeId(employeeId);
        setJobId(jobId);
        setManagerId(managerId);
        setDepartmentId(departmentId);
        setLocationId(locationId);
        setCountryId(countryId);
        setFirstName(firstName);
        setLastName(lastName);
        setSalary(salary);
        setCommissionPct(commissionPct);
        setDepartmentName(departmentName);
        setJobTitle(jobTitle);
        setCity(city);
        setStateProvince(stateProvince);
        setCountryName(countryName);
        setRegionName(regionName);
        resetTouchedOnNotNull();
    }
}
