/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Employees;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.EMPLOYEES.EMPLOYEE_ID</code>.
     */
    public void setEmployeeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.EMPLOYEE_ID</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.PHONE_NUMBER</code>.
     */
    public void setPhoneNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.PHONE_NUMBER</code>.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.HIRE_DATE</code>.
     */
    public void setHireDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.HIRE_DATE</code>.
     */
    public LocalDateTime getHireDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.JOB_ID</code>.
     */
    public void setJobId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.JOB_ID</code>.
     */
    public String getJobId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.SALARY</code>.
     */
    public void setSalary(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.SALARY</code>.
     */
    public BigDecimal getSalary() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.COMMISSION_PCT</code>.
     */
    public void setCommissionPct(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.COMMISSION_PCT</code>.
     */
    public BigDecimal getCommissionPct() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.MANAGER_ID</code>.
     */
    public void setManagerId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.MANAGER_ID</code>.
     */
    public Long getManagerId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>HR.EMPLOYEES.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>HR.EMPLOYEES.DEPARTMENT_ID</code>.
     */
    public Long getDepartmentId() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Long employeeId, String firstName, String lastName, String email, String phoneNumber, LocalDateTime hireDate, String jobId, BigDecimal salary, BigDecimal commissionPct, Long managerId, Long departmentId) {
        super(Employees.EMPLOYEES);

        setEmployeeId(employeeId);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPhoneNumber(phoneNumber);
        setHireDate(hireDate);
        setJobId(jobId);
        setSalary(salary);
        setCommissionPct(commissionPct);
        setManagerId(managerId);
        setDepartmentId(departmentId);
        resetTouchedOnNotNull();
    }
}
