/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;


import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.JobHistory;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobHistoryRecord extends UpdatableRecordImpl<JobHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.JOB_HISTORY.EMPLOYEE_ID</code>.
     */
    public void setEmployeeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.JOB_HISTORY.EMPLOYEE_ID</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>HR.JOB_HISTORY.START_DATE</code>.
     */
    public void setStartDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.JOB_HISTORY.START_DATE</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>HR.JOB_HISTORY.END_DATE</code>.
     */
    public void setEndDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.JOB_HISTORY.END_DATE</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>HR.JOB_HISTORY.JOB_ID</code>.
     */
    public void setJobId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>HR.JOB_HISTORY.JOB_ID</code>.
     */
    public String getJobId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>HR.JOB_HISTORY.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>HR.JOB_HISTORY.DEPARTMENT_ID</code>.
     */
    public Long getDepartmentId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, LocalDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobHistoryRecord
     */
    public JobHistoryRecord() {
        super(JobHistory.JOB_HISTORY);
    }

    /**
     * Create a detached, initialised JobHistoryRecord
     */
    public JobHistoryRecord(Long employeeId, LocalDateTime startDate, LocalDateTime endDate, String jobId, Long departmentId) {
        super(JobHistory.JOB_HISTORY);

        setEmployeeId(employeeId);
        setStartDate(startDate);
        setEndDate(endDate);
        setJobId(jobId);
        setDepartmentId(departmentId);
        resetTouchedOnNotNull();
    }
}
