/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Jobs;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JobsRecord
        extends UpdatableRecordImpl<JobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.JOBS.JOB_ID</code>.
     */
    public void setJobId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.JOBS.JOB_ID</code>.
     */
    public String getJobId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>HR.JOBS.JOB_TITLE</code>.
     */
    public void setJobTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.JOBS.JOB_TITLE</code>.
     */
    public String getJobTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>HR.JOBS.MIN_SALARY</code>.
     */
    public void setMinSalary(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.JOBS.MIN_SALARY</code>.
     */
    public BigDecimal getMinSalary() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>HR.JOBS.MAX_SALARY</code>.
     */
    public void setMaxSalary(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>HR.JOBS.MAX_SALARY</code>.
     */
    public BigDecimal getMaxSalary() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobsRecord
     */
    public JobsRecord() {
        super(Jobs.JOBS);
    }

    /**
     * Create a detached, initialised JobsRecord
     */
    public JobsRecord(String jobId, String jobTitle, BigDecimal minSalary, BigDecimal maxSalary) {
        super(Jobs.JOBS);

        setJobId(jobId);
        setJobTitle(jobTitle);
        setMinSalary(minSalary);
        setMaxSalary(maxSalary);
        resetTouchedOnNotNull();
    }
}
