/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Locations;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LocationsRecord
        extends UpdatableRecordImpl<LocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.LOCATIONS.LOCATION_ID</code>.
     */
    public void setLocationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.LOCATIONS.LOCATION_ID</code>.
     */
    public Long getLocationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>HR.LOCATIONS.STREET_ADDRESS</code>.
     */
    public void setStreetAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.LOCATIONS.STREET_ADDRESS</code>.
     */
    public String getStreetAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>HR.LOCATIONS.POSTAL_CODE</code>.
     */
    public void setPostalCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>HR.LOCATIONS.POSTAL_CODE</code>.
     */
    public String getPostalCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>HR.LOCATIONS.CITY</code>.
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>HR.LOCATIONS.CITY</code>.
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>HR.LOCATIONS.STATE_PROVINCE</code>.
     */
    public void setStateProvince(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>HR.LOCATIONS.STATE_PROVINCE</code>.
     */
    public String getStateProvince() {
        return (String) get(4);
    }

    /**
     * Setter for <code>HR.LOCATIONS.COUNTRY_ID</code>.
     */
    public void setCountryId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>HR.LOCATIONS.COUNTRY_ID</code>.
     */
    public String getCountryId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationsRecord
     */
    public LocationsRecord() {
        super(Locations.LOCATIONS);
    }

    /**
     * Create a detached, initialised LocationsRecord
     */
    public LocationsRecord(Long locationId, String streetAddress, String postalCode, String city, String stateProvince,
                           String countryId) {
        super(Locations.LOCATIONS);

        setLocationId(locationId);
        setStreetAddress(streetAddress);
        setPostalCode(postalCode);
        setCity(city);
        setStateProvince(stateProvince);
        setCountryId(countryId);
        resetTouchedOnNotNull();
    }
}
