/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Regions;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class RegionsRecord
        extends UpdatableRecordImpl<RegionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>HR.REGIONS.REGION_ID</code>.
     */
    public void setRegionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>HR.REGIONS.REGION_ID</code>.
     */
    public Long getRegionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>HR.REGIONS.REGION_NAME</code>.
     */
    public void setRegionName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>HR.REGIONS.REGION_NAME</code>.
     */
    public String getRegionName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegionsRecord
     */
    public RegionsRecord() {
        super(Regions.REGIONS);
    }

    /**
     * Create a detached, initialised RegionsRecord
     */
    public RegionsRecord(Long regionId, String regionName) {
        super(Regions.REGIONS);

        setRegionId(regionId);
        setRegionName(regionName);
        resetTouchedOnNotNull();
    }
}
