/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.CustomerOrderProducts;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Customers;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Inventory;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.OrderItems;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Orders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.ProductOrders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.ProductReviews;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Products;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Shipments;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.StoreOrders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Stores;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Co
        extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CO</code>
     */
    public static final Co CO = new Co();

    /**
     * The table <code>CO.CUSTOMER_ORDER_PRODUCTS</code>.
     */
    public final CustomerOrderProducts CUSTOMER_ORDER_PRODUCTS = CustomerOrderProducts.CUSTOMER_ORDER_PRODUCTS;

    /**
     * The table <code>CO.CUSTOMERS</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>CO.INVENTORY</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>CO.ORDER_ITEMS</code>.
     */
    public final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>CO.ORDERS</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>CO.PRODUCT_ORDERS</code>.
     */
    public final ProductOrders PRODUCT_ORDERS = ProductOrders.PRODUCT_ORDERS;

    /**
     * The table <code>CO.PRODUCT_REVIEWS</code>.
     */
    public final ProductReviews PRODUCT_REVIEWS = ProductReviews.PRODUCT_REVIEWS;

    /**
     * The table <code>CO.PRODUCTS</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>CO.SHIPMENTS</code>.
     */
    public final Shipments SHIPMENTS = Shipments.SHIPMENTS;

    /**
     * The table <code>CO.STORE_ORDERS</code>.
     */
    public final StoreOrders STORE_ORDERS = StoreOrders.STORE_ORDERS;

    /**
     * The table <code>CO.STORES</code>.
     */
    public final Stores STORES = Stores.STORES;

    /**
     * No further instances allowed
     */
    private Co() {
        super(DSL.name("CO"), null, DSL.comment(""));
    }

    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                CustomerOrderProducts.CUSTOMER_ORDER_PRODUCTS,
                Customers.CUSTOMERS,
                Inventory.INVENTORY,
                OrderItems.ORDER_ITEMS,
                Orders.ORDERS,
                ProductOrders.PRODUCT_ORDERS,
                ProductReviews.PRODUCT_REVIEWS,
                Products.PRODUCTS,
                Shipments.SHIPMENTS,
                StoreOrders.STORE_ORDERS,
                Stores.STORES
        );
    }
}
