/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Customers;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Inventory;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.OrderItems;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Orders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Products;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Shipments;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Stores;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.CustomersRecord;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.InventoryRecord;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.OrderItemsRecord;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.OrdersRecord;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.ProductsRecord;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.ShipmentsRecord;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records.StoresRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in CO.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> PK_CUSTOMERS =
            Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("PK_CUSTOMERS"),
                                     new TableField[]{Customers.CUSTOMERS.CUSTOMER_ID}, true);

    public static final UniqueKey<InventoryRecord> PK_INVENTORY =
            Internal.createUniqueKey(Inventory.INVENTORY, DSL.name("PK_INVENTORY"),
                                     new TableField[]{Inventory.INVENTORY.INVENTORY_ID}, true);

    public static final UniqueKey<OrderItemsRecord> PK_ORDER_ITEMS =
            Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("PK_ORDER_ITEMS"),
                                     new TableField[]{OrderItems.ORDER_ITEMS.ORDER_ID,
                                             OrderItems.ORDER_ITEMS.LINE_ITEM_ID},
                                     true);

    public static final UniqueKey<OrdersRecord> PK_ORDERS =
            Internal.createUniqueKey(Orders.ORDERS, DSL.name("PK_ORDERS"), new TableField[]{Orders.ORDERS.ORDER_ID},
                                     true);

    public static final UniqueKey<ProductsRecord> PK_PRODUCTS =
            Internal.createUniqueKey(Products.PRODUCTS, DSL.name("PK_PRODUCTS"),
                                     new TableField[]{Products.PRODUCTS.PRODUCT_ID}, true);

    public static final UniqueKey<ShipmentsRecord> PK_SHIPMENTS =
            Internal.createUniqueKey(Shipments.SHIPMENTS, DSL.name("PK_SHIPMENTS"),
                                     new TableField[]{Shipments.SHIPMENTS.SHIPMENT_ID}, true);

    public static final UniqueKey<StoresRecord> PK_STORES =
            Internal.createUniqueKey(Stores.STORES, DSL.name("PK_STORES"), new TableField[]{Stores.STORES.STORE_ID},
                                     true);
}
