/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.CustomerOrderProducts;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Customers;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Inventory;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.OrderItems;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Orders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.ProductOrders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.ProductReviews;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Products;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Shipments;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.StoreOrders;
import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Stores;

/**
 * Convenience access to all tables in CO.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>CO.CUSTOMER_ORDER_PRODUCTS</code>.
     */
    public static final CustomerOrderProducts CUSTOMER_ORDER_PRODUCTS = CustomerOrderProducts.CUSTOMER_ORDER_PRODUCTS;

    /**
     * The table <code>CO.CUSTOMERS</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>CO.INVENTORY</code>.
     */
    public static final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>CO.ORDER_ITEMS</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>CO.ORDERS</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>CO.PRODUCT_ORDERS</code>.
     */
    public static final ProductOrders PRODUCT_ORDERS = ProductOrders.PRODUCT_ORDERS;

    /**
     * The table <code>CO.PRODUCT_REVIEWS</code>.
     */
    public static final ProductReviews PRODUCT_REVIEWS = ProductReviews.PRODUCT_REVIEWS;

    /**
     * The table <code>CO.PRODUCTS</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>CO.SHIPMENTS</code>.
     */
    public static final Shipments SHIPMENTS = Shipments.SHIPMENTS;

    /**
     * The table <code>CO.STORE_ORDERS</code>.
     */
    public static final StoreOrders STORE_ORDERS = StoreOrders.STORE_ORDERS;

    /**
     * The table <code>CO.STORES</code>.
     */
    public static final Stores STORES = Stores.STORES;
}
