package com.github.jinahya.oracle.sample.schemas.co.data;

import com.github.jinahya.oracle.sample.schemas.persistence.co.Customer;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Customer_;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * A repository for {@link Customer}, the {@code CUSTOMERS} table of the Customer Orders schema.
 * <p>
 * The id is a {@link Long} generated by the database ({@code GenerationType.IDENTITY}), so a newly constructed customer
 * is saved with no id, and the id is set on the saved instance.
 * <p>
 * {@link JpaSpecificationExecutor} is here for criteria queries. Name the attributes through the generated static
 * metamodel rather than by string, for example
 * {@code (root, query, builder) -> builder.equal(root.get(Customer_.fullName), name)}.
 * <p>
 * {@link Customer} also declares named queries, each named {@code Customer.<query name>}. JPA does not require that
 * prefix, only that a name be unique in the persistence unit, but it is the usual convention, and it is what Spring
 * Data's lookup builds on: a method named after the query, such as {@link #selectOneByEmailAddress(String)}, runs it
 * with no annotation. A method named otherwise can still run one through {@code @Query(name = ...)}.
 *
 * @see Customer
 * @see Customer_
 */
@Repository
public interface CustomerRepository
        extends JpaRepository<Customer, Long>,
                JpaSpecificationExecutor<Customer> {

    /**
     * Selects the customer with the specified value of {@link Customer_#EMAIL_ADDRESS} attribute, through the
     * {@code Customer.selectOneByEmailAddress} named query of {@link Customer}.
     * <p>
     * Spring Data looks a named query up by {@code <entity name>.<method name>} before it tries to derive one from the
     * method name, so this method's name has to stay in step with the query's. The prefix is the entity name, which is
     * the simple class name here only because {@link Customer} declares a bare {@code @Entity}.
     * <p>
     * The query binds {@code :emailAddress} by name. The module compiles with {@code -parameters}, so the parameter's
     * own name would do; the {@link Param} ties the argument to it regardless of that flag. Without both, the argument
     * would be bound by position, as {@code ?1}, and the call would fail with an
     * {@code InvalidDataAccessApiUsageException}, though the context starts either way.
     *
     * @param emailAddress the value of the {@link Customer_#EMAIL_ADDRESS} attribute to match; must not be
     *                     {@code null}.
     * @return the customer with {@code emailAddress}, or an empty optional if there is none.
     * @see #findByEmailAddress(String)
     */
    Optional<Customer> selectOneByEmailAddress(@Param("emailAddress") String emailAddress);

    // -----------------------------------------------------------------------------------------------------------------

    /**
     * Finds the customer with the specified value of {@link Customer_#EMAIL_ADDRESS} attribute.
     * <p>
     * The address is the customer's business key: {@code EMAIL_ADDRESS} is mapped {@code unique}, and it is what
     * {@link Customer#equals(Object)} compares. So there is at most one match, and an {@link Optional} return is safe.
     * The comparison is the database's, which is case-sensitive on Oracle by default.
     * <p>
     * The query is derived from the method name. It does what {@link #selectOneByEmailAddress(String)} does, without
     * the named query.
     *
     * @param emailAddress the value of the {@link Customer_#EMAIL_ADDRESS} attribute to match; must not be
     *                     {@code null}.
     * @return the customer with {@code emailAddress}, or an empty optional if there is none.
     * @see #selectOneByEmailAddress(String)
     */
    Optional<Customer> findByEmailAddress(String emailAddress);
}
