package com.github.jinahya.oracle.sample.schemas.co.data;

import com.github.jinahya.oracle.sample.schemas.persistence.co.Inventory;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Inventory_;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Product;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Store;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * A repository for {@link Inventory}, the {@code INVENTORY} table of the Customer Orders schema.
 * <p>
 * An inventory is the stock of one {@link Product} at one {@link Store}; the table is unique on that pair. The id is a
 * {@link Long} generated by the database ({@code GenerationType.IDENTITY}), so a newly constructed inventory is saved
 * with no id, and the id is set on the saved instance.
 * <p>
 * Both associations are {@code LAZY}: an inventory found here carries its store and product as uninitialized proxies,
 * which load on first access, and only inside a transaction; outside one, that access fails with a
 * {@code LazyInitializationException}.
 * <p>
 * {@link JpaSpecificationExecutor} is here for criteria queries. Name the attributes through the generated static
 * metamodel rather than by string, for example
 * {@code (root, query, builder) -> builder.equal(root.get(Inventory_.store), store)}.
 *
 * @see Inventory
 * @see Inventory_
 */
@Repository
public interface InventoryRepository
        extends JpaRepository<Inventory, Long>,
                JpaSpecificationExecutor<Inventory> {

    /**
     * Finds the inventory whose value of {@link Inventory_#STORE} attribute is the specified store, and whose value of
     * {@link Inventory_#PRODUCT} attribute is the specified product.
     * <p>
     * The query is derived from the method name, and compares the {@code STORE_ID} and {@code PRODUCT_ID} columns with
     * the ids of the two; neither is loaded, so references from {@link StoreRepository#getReferenceById(Object)} and
     * {@link ProductRepository#getReferenceById(Object)} do as well as loaded entities. The table being unique on store
     * and product, at most one inventory matches.
     *
     * @param store   the store of the inventory; must not be {@code null}.
     * @param product the product of the inventory; must not be {@code null}.
     * @return an optional of the inventory of {@code product} at {@code store}; empty if the store does not stock the
     *         product.
     * @see #findAllByStore(Store, Pageable)
     * @see #findAllByProduct(Product, Pageable)
     */
    Optional<Inventory> findByStoreAndProduct(Store store, Product product);

    /**
     * Finds the inventories whose value of {@link Inventory_#STORE} attribute is the specified store.
     * <p>
     * The query is derived from the method name, and compares the {@code STORE_ID} column with the store's id; the
     * store itself is not loaded, so a reference from {@link StoreRepository#getReferenceById(Object)} does as well
     * as a loaded store. The table being unique on store and product, the page holds each product at most
     * once.
     * <p>
     * The page carries a count of all matches, which Spring Data gets with a second, {@code COUNT} query; it skips that
     * query when the first page is not full. The query has no order of its own, so give {@code pageable} a sort, such
     * as by {@link Inventory_#INVENTORY_ID}, or the pages are not stable.
     *
     * @param store    the store whose inventories are found; must not be {@code null}.
     * @param pageable the page to return, and its sort; {@link Pageable#unpaged()} for all matches in one page. Must
     *                 not be {@code null}.
     * @return a page of the inventories of {@code store}.
     * @see #findAllByProduct(Product, Pageable)
     */
    Page<Inventory> findAllByStore(Store store, Pageable pageable);

    /**
     * Finds the inventories whose value of {@link Inventory_#PRODUCT} attribute is the specified product.
     * <p>
     * The query is derived from the method name, and compares the {@code PRODUCT_ID} column with the product's id; the
     * product itself is not loaded, so a reference from {@link ProductRepository#getReferenceById(Object)} does as well
     * as a loaded product. The table being unique on store and product, the page holds each store at most once.
     * <p>
     * The page carries a count of all matches, which Spring Data gets with a second, {@code COUNT} query; it skips that
     * query when the first page is not full. The query has no order of its own, so give {@code pageable} a sort, such
     * as by {@link Inventory_#INVENTORY_ID}, or the pages are not stable.
     *
     * @param product  the product whose inventories are found; must not be {@code null}.
     * @param pageable the page to return, and its sort; {@link Pageable#unpaged()} for all matches in one page. Must
     *                 not be {@code null}.
     * @return a page of the inventories of {@code product}.
     * @see #findAllByStore(Store, Pageable)
     */
    Page<Inventory> findAllByProduct(Product product, Pageable pageable);
}
