package com.github.jinahya.oracle.sample.schemas.co.data;

import com.github.jinahya.oracle.sample.schemas.persistence.co.Customer;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Order;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Order_;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Store;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * A repository for {@link Order}, the {@code ORDERS} table of the Customer Orders schema.
 * <p>
 * An order is placed by one {@link Customer} at one {@link Store}. The id is a {@link Long} generated by the database
 * ({@code GenerationType.IDENTITY}), so a newly constructed order is saved with no id, and the id is set on the saved
 * instance.
 * <p>
 * Both associations are {@code LAZY}: an order found here carries its customer and store as uninitialized proxies,
 * which load on first access, and only inside a transaction; outside one, that access fails with a
 * {@code LazyInitializationException}.
 * <p>
 * {@link JpaSpecificationExecutor} is here for criteria queries. Name the attributes through the generated static
 * metamodel rather than by string, for example
 * {@code (root, query, builder) -> builder.equal(root.get(Order_.customer), customer)}.
 * <p>
 * {@link Order} declares named queries too ({@code Order.selectListByCustomerOrderByOrderTmsDesc},
 * {@code Order.selectListByCustomerOderIdGtOrderByOrderTmsDesc} and {@code Order.countByCustomerOrderByOrderTmsDesc}),
 * but no method here runs them. One that does is named after the query, as in {@link CustomerRepository}, and binds its
 * parameters with {@code @Param}. The methods below derive their queries from their names instead.
 *
 * @see Order
 * @see Order_
 */
@Repository
public interface OrderRepository
        extends JpaRepository<Order, Long>,
                JpaSpecificationExecutor<Order> {

    /**
     * Finds the orders whose value of {@link Order_#CUSTOMER} attribute is the specified customer.
     * <p>
     * The query is derived from the method name, and compares the {@code CUSTOMER_ID} column with the customer's id;
     * the customer itself is not loaded, so a reference from {@link CustomerRepository#getReferenceById(Object)} does as
     * well as a loaded customer.
     * <p>
     * The page carries a count of all matches, which Spring Data gets with a second, {@code COUNT} query; it skips that
     * query when the first page is not full. The query has no order of its own, so give {@code pageable} a sort, such
     * as by {@link Order_#ORDER_TMS} descending for the latest first, or the pages are not stable.
     *
     * @param customer the customer whose orders are found; must not be {@code null}.
     * @param pageable the page to return, and its sort; {@link Pageable#unpaged()} for all matches in one page. Must
     *                 not be {@code null}.
     * @return a page of the orders of {@code customer}.
     * @see #findAllByCustomerAndStore(Customer, Store, Pageable)
     */
    Page<Order> findAllByCustomer(Customer customer, Pageable pageable);

    /**
     * Finds the orders whose value of {@link Order_#CUSTOMER} attribute is the specified customer, the latest first.
     * <p>
     * The {@code OrderBy} of the method name is fixed, and the sort of {@code pageable} is appended to it rather than
     * replacing it: a sort by {@code orderId} renders {@code ORDER BY order_tms DESC, order_id}, and one by
     * {@code orderTms} ascending changes nothing. So the caller can break ties, but cannot change the order.
     *
     * @param customer the customer whose orders are found; must not be {@code null}.
     * @param pageable the page to return, and a sort to break ties with; must not be {@code null}.
     * @return a page of the orders of {@code customer}, the latest first.
     * @deprecated Use {@link #findAllByCustomer(Customer, Pageable)} with a {@code pageable} sorted by
     *             {@link Order_#ORDER_TMS} descending, which the caller can change.
     */
    @Deprecated(forRemoval = true)
    Page<Order> findAllByCustomerOrderByOrderTmsDesc(Customer customer, Pageable pageable);

    /**
     * Finds the orders whose value of {@link Order_#STORE} attribute is the specified store.
     * <p>
     * The query is derived from the method name, and compares the {@code STORE_ID} column with the store's id; the
     * store itself is not loaded, so a reference from {@link StoreRepository#getReferenceById(Object)} does as well as
     * a loaded store.
     * <p>
     * The page carries a count of all matches, which Spring Data gets with a second, {@code COUNT} query; it skips that
     * query when the first page is not full. The query has no order of its own, so give {@code pageable} a sort, such
     * as by {@link Order_#ORDER_TMS} descending for the latest first, or the pages are not stable.
     *
     * @param store    the store whose orders are found; must not be {@code null}.
     * @param pageable the page to return, and its sort; {@link Pageable#unpaged()} for all matches in one page. Must
     *                 not be {@code null}.
     * @return a page of the orders placed at {@code store}.
     * @see #findAllByCustomerAndStore(Customer, Store, Pageable)
     */
    Page<Order> findAllByStore(Store store, Pageable pageable);

    // -----------------------------------------------------------------------------------------------------------------

    /**
     * Finds the orders whose value of {@link Order_#CUSTOMER} attribute is the specified customer, and whose value of
     * {@link Order_#STORE} attribute is the specified store.
     * <p>
     * The query is derived from the method name, and compares the {@code CUSTOMER_ID} and {@code STORE_ID} columns
     * with the ids of the two; neither is loaded, so references do as well as loaded entities. Unlike an inventory, an
     * order is not unique on the pair, so this is a page, not an optional.
     * <p>
     * The page carries a count of all matches, which Spring Data gets with a second, {@code COUNT} query; it skips that
     * query when the first page is not full. The query has no order of its own, so give {@code pageable} a sort, such
     * as by {@link Order_#ORDER_TMS} descending for the latest first, or the pages are not stable.
     *
     * @param customer the customer whose orders are found; must not be {@code null}.
     * @param store    the store the orders were placed at; must not be {@code null}.
     * @param pageable the page to return, and its sort; {@link Pageable#unpaged()} for all matches in one page. Must
     *                 not be {@code null}.
     * @return a page of the orders of {@code customer} placed at {@code store}.
     * @see #findAllByCustomer(Customer, Pageable)
     * @see #findAllByStore(Store, Pageable)
     */
    Page<Order> findAllByCustomerAndStore(Customer customer, Store store, Pageable pageable);

    /**
     * Finds the orders whose value of {@link Order_#STORE} attribute is the specified store, and whose value of
     * {@link Order_#CUSTOMER} attribute is the specified customer.
     * <p>
     * The same query as {@link #findAllByCustomerAndStore(Customer, Store, Pageable)}, with the parameters the other way
     * round.
     *
     * @param store    the store the orders were placed at; must not be {@code null}.
     * @param customer the customer whose orders are found; must not be {@code null}.
     * @param pageable the page to return, and its sort; must not be {@code null}.
     * @return a page of the orders of {@code customer} placed at {@code store}.
     * @deprecated Use {@link #findAllByCustomerAndStore(Customer, Store, Pageable)}, which is the same query.
     */
    @Deprecated(forRemoval = true)
    Page<Order> findAllByStoreAndCustomer(Store store, Customer customer, Pageable pageable);
}
