package com.github.jinahya.oracle.sample.schemas.co.data;

import com.github.jinahya.oracle.sample.schemas.persistence.co.Product;
import com.github.jinahya.oracle.sample.schemas.persistence.co.Product_;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * A repository for {@link Product}, the {@code PRODUCTS} table of the Customer Orders schema.
 * <p>
 * The id is a {@link Long} generated by the database ({@code GenerationType.IDENTITY}), so a newly constructed product
 * is saved with no id, and the id is set on the saved instance. Unlike {@code Customer}, a product has no business key:
 * {@link Product#equals(Object)} compares ids, so two unsaved products are never equal.
 * <p>
 * {@link JpaSpecificationExecutor} is here for criteria queries. Name the attributes through the generated static
 * metamodel rather than by string, for example
 * {@code (root, query, builder) -> builder.equal(root.get(Product_.productName), name)}.
 * <p>
 * {@link Product} declares named queries too ({@code Product.selectListOrderByProductIdAsc} and
 * {@code Product.selectListOrderByProductIdAscProductIdGt}), but no method here runs them yet. One that does is named
 * after the query, as in {@link CustomerRepository}.
 *
 * @see Product
 * @see Product_
 */
@Repository
public interface ProductRepository
        extends JpaRepository<Product, Long>,
                JpaSpecificationExecutor<Product> {

}
