/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.CustomerOrderProducts;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CustomerOrderProductsRecord
        extends TableRecordImpl<CustomerOrderProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_ID</code>.
     */
    public void setOrderId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_ID</code>.
     */
    public Long getOrderId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_TMS</code>.
     */
    public void setOrderTms(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_TMS</code>.
     */
    public LocalDateTime getOrderTms() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_STATUS</code>.
     */
    public void setOrderStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_STATUS</code>.
     */
    public String getOrderStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.EMAIL_ADDRESS</code>.
     */
    public void setEmailAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.EMAIL_ADDRESS</code>.
     */
    public String getEmailAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.FULL_NAME</code>.
     */
    public void setFullName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.FULL_NAME</code>.
     */
    public String getFullName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_TOTAL</code>.
     */
    public void setOrderTotal(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ORDER_TOTAL</code>.
     */
    public BigDecimal getOrderTotal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ITEMS</code>.
     */
    public void setItems(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CO.CUSTOMER_ORDER_PRODUCTS.ITEMS</code>.
     */
    public String getItems() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerOrderProductsRecord
     */
    public CustomerOrderProductsRecord() {
        super(CustomerOrderProducts.CUSTOMER_ORDER_PRODUCTS);
    }

    /**
     * Create a detached, initialised CustomerOrderProductsRecord
     */
    public CustomerOrderProductsRecord(Long orderId, LocalDateTime orderTms, String orderStatus, Long customerId,
                                       String emailAddress, String fullName, BigDecimal orderTotal, String items) {
        super(CustomerOrderProducts.CUSTOMER_ORDER_PRODUCTS);

        setOrderId(orderId);
        setOrderTms(orderTms);
        setOrderStatus(orderStatus);
        setCustomerId(customerId);
        setEmailAddress(emailAddress);
        setFullName(fullName);
        setOrderTotal(orderTotal);
        setItems(items);
        resetTouchedOnNotNull();
    }
}
