/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Customers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CustomersRecord
        extends UpdatableRecordImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.CUSTOMERS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.CUSTOMERS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.CUSTOMERS.EMAIL_ADDRESS</code>.
     */
    public void setEmailAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.CUSTOMERS.EMAIL_ADDRESS</code>.
     */
    public String getEmailAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CO.CUSTOMERS.FULL_NAME</code>.
     */
    public void setFullName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.CUSTOMERS.FULL_NAME</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Long customerId, String emailAddress, String fullName) {
        super(Customers.CUSTOMERS);

        setCustomerId(customerId);
        setEmailAddress(emailAddress);
        setFullName(fullName);
        resetTouchedOnNotNull();
    }
}
