/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Inventory;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class InventoryRecord
        extends UpdatableRecordImpl<InventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.INVENTORY.INVENTORY_ID</code>.
     */
    public void setInventoryId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.INVENTORY.INVENTORY_ID</code>.
     */
    public Long getInventoryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.INVENTORY.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.INVENTORY.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>CO.INVENTORY.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.INVENTORY.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>CO.INVENTORY.PRODUCT_INVENTORY</code>.
     */
    public void setProductInventory(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.INVENTORY.PRODUCT_INVENTORY</code>.
     */
    public BigDecimal getProductInventory() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(Long inventoryId, Long storeId, Long productId, BigDecimal productInventory) {
        super(Inventory.INVENTORY);

        setInventoryId(inventoryId);
        setStoreId(storeId);
        setProductId(productId);
        setProductInventory(productInventory);
        resetTouchedOnNotNull();
    }
}
