/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.OrderItems;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class OrderItemsRecord
        extends UpdatableRecordImpl<OrderItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.ORDER_ITEMS.ORDER_ID</code>.
     */
    public void setOrderId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.ORDER_ITEMS.ORDER_ID</code>.
     */
    public Long getOrderId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.ORDER_ITEMS.LINE_ITEM_ID</code>.
     */
    public void setLineItemId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.ORDER_ITEMS.LINE_ITEM_ID</code>.
     */
    public Long getLineItemId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>CO.ORDER_ITEMS.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.ORDER_ITEMS.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>CO.ORDER_ITEMS.UNIT_PRICE</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.ORDER_ITEMS.UNIT_PRICE</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>CO.ORDER_ITEMS.QUANTITY</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.ORDER_ITEMS.QUANTITY</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>CO.ORDER_ITEMS.SHIPMENT_ID</code>.
     */
    public void setShipmentId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>CO.ORDER_ITEMS.SHIPMENT_ID</code>.
     */
    public Long getShipmentId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemsRecord
     */
    public OrderItemsRecord() {
        super(OrderItems.ORDER_ITEMS);
    }

    /**
     * Create a detached, initialised OrderItemsRecord
     */
    public OrderItemsRecord(Long orderId, Long lineItemId, Long productId, BigDecimal unitPrice, BigDecimal quantity,
                            Long shipmentId) {
        super(OrderItems.ORDER_ITEMS);

        setOrderId(orderId);
        setLineItemId(lineItemId);
        setProductId(productId);
        setUnitPrice(unitPrice);
        setQuantity(quantity);
        setShipmentId(shipmentId);
        resetTouchedOnNotNull();
    }
}
