/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Orders;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class OrdersRecord
        extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.ORDERS.ORDER_ID</code>.
     */
    public void setOrderId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.ORDERS.ORDER_ID</code>.
     */
    public Long getOrderId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.ORDERS.ORDER_TMS</code>.
     */
    public void setOrderTms(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.ORDERS.ORDER_TMS</code>.
     */
    public LocalDateTime getOrderTms() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CO.ORDERS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.ORDERS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>CO.ORDERS.ORDER_STATUS</code>.
     */
    public void setOrderStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.ORDERS.ORDER_STATUS</code>.
     */
    public String getOrderStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CO.ORDERS.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.ORDERS.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Long orderId, LocalDateTime orderTms, Long customerId, String orderStatus, Long storeId) {
        super(Orders.ORDERS);

        setOrderId(orderId);
        setOrderTms(orderTms);
        setCustomerId(customerId);
        setOrderStatus(orderStatus);
        setStoreId(storeId);
        resetTouchedOnNotNull();
    }
}
