/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.ProductReviews;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProductReviewsRecord
        extends TableRecordImpl<ProductReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.PRODUCT_REVIEWS.PRODUCT_NAME</code>.
     */
    public void setProductName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_REVIEWS.PRODUCT_NAME</code>.
     */
    public String getProductName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CO.PRODUCT_REVIEWS.RATING</code>.
     */
    public void setRating(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_REVIEWS.RATING</code>.
     */
    public BigDecimal getRating() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>CO.PRODUCT_REVIEWS.AVG_RATING</code>.
     */
    public void setAvgRating(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_REVIEWS.AVG_RATING</code>.
     */
    public BigDecimal getAvgRating() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>CO.PRODUCT_REVIEWS.REVIEW</code>.
     */
    public void setReview(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_REVIEWS.REVIEW</code>.
     */
    public String getReview() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductReviewsRecord
     */
    public ProductReviewsRecord() {
        super(ProductReviews.PRODUCT_REVIEWS);
    }

    /**
     * Create a detached, initialised ProductReviewsRecord
     */
    public ProductReviewsRecord(String productName, BigDecimal rating, BigDecimal avgRating, String review) {
        super(ProductReviews.PRODUCT_REVIEWS);

        setProductName(productName);
        setRating(rating);
        setAvgRating(avgRating);
        setReview(review);
        resetTouchedOnNotNull();
    }
}
