/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Products;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProductsRecord
        extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.PRODUCTS.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.PRODUCTS.PRODUCT_NAME</code>.
     */
    public void setProductName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.PRODUCT_NAME</code>.
     */
    public String getProductName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CO.PRODUCTS.UNIT_PRICE</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.UNIT_PRICE</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>CO.PRODUCTS.PRODUCT_DETAILS</code>.
     */
    public void setProductDetails(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.PRODUCT_DETAILS</code>.
     */
    public byte[] getProductDetails() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>CO.PRODUCTS.PRODUCT_IMAGE</code>.
     */
    public void setProductImage(byte[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.PRODUCT_IMAGE</code>.
     */
    public byte[] getProductImage() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>CO.PRODUCTS.IMAGE_MIME_TYPE</code>.
     */
    public void setImageMimeType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.IMAGE_MIME_TYPE</code>.
     */
    public String getImageMimeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CO.PRODUCTS.IMAGE_FILENAME</code>.
     */
    public void setImageFilename(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.IMAGE_FILENAME</code>.
     */
    public String getImageFilename() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CO.PRODUCTS.IMAGE_CHARSET</code>.
     */
    public void setImageCharset(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.IMAGE_CHARSET</code>.
     */
    public String getImageCharset() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CO.PRODUCTS.IMAGE_LAST_UPDATED</code>.
     */
    public void setImageLastUpdated(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>CO.PRODUCTS.IMAGE_LAST_UPDATED</code>.
     */
    public LocalDateTime getImageLastUpdated() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Long productId, String productName, BigDecimal unitPrice, byte[] productDetails,
                          byte[] productImage, String imageMimeType, String imageFilename, String imageCharset,
                          LocalDateTime imageLastUpdated) {
        super(Products.PRODUCTS);

        setProductId(productId);
        setProductName(productName);
        setUnitPrice(unitPrice);
        setProductDetails(productDetails);
        setProductImage(productImage);
        setImageMimeType(imageMimeType);
        setImageFilename(imageFilename);
        setImageCharset(imageCharset);
        setImageLastUpdated(imageLastUpdated);
        resetTouchedOnNotNull();
    }
}
