/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.ProductOrders;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProductOrdersRecord
        extends TableRecordImpl<ProductOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.PRODUCT_ORDERS.PRODUCT_NAME</code>.
     */
    public void setProductName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_ORDERS.PRODUCT_NAME</code>.
     */
    public String getProductName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CO.PRODUCT_ORDERS.ORDER_STATUS</code>.
     */
    public void setOrderStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_ORDERS.ORDER_STATUS</code>.
     */
    public String getOrderStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CO.PRODUCT_ORDERS.TOTAL_SALES</code>.
     */
    public void setTotalSales(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_ORDERS.TOTAL_SALES</code>.
     */
    public BigDecimal getTotalSales() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>CO.PRODUCT_ORDERS.ORDER_COUNT</code>.
     */
    public void setOrderCount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.PRODUCT_ORDERS.ORDER_COUNT</code>.
     */
    public BigDecimal getOrderCount() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductOrdersRecord
     */
    public ProductOrdersRecord() {
        super(ProductOrders.PRODUCT_ORDERS);
    }

    /**
     * Create a detached, initialised ProductOrdersRecord
     */
    public ProductOrdersRecord(String productName, String orderStatus, BigDecimal totalSales, BigDecimal orderCount) {
        super(ProductOrders.PRODUCT_ORDERS);

        setProductName(productName);
        setOrderStatus(orderStatus);
        setTotalSales(totalSales);
        setOrderCount(orderCount);
        resetTouchedOnNotNull();
    }
}
