/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Shipments;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ShipmentsRecord
        extends UpdatableRecordImpl<ShipmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.SHIPMENTS.SHIPMENT_ID</code>.
     */
    public void setShipmentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.SHIPMENTS.SHIPMENT_ID</code>.
     */
    public Long getShipmentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.SHIPMENTS.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.SHIPMENTS.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>CO.SHIPMENTS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.SHIPMENTS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>CO.SHIPMENTS.DELIVERY_ADDRESS</code>.
     */
    public void setDeliveryAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.SHIPMENTS.DELIVERY_ADDRESS</code>.
     */
    public String getDeliveryAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CO.SHIPMENTS.SHIPMENT_STATUS</code>.
     */
    public void setShipmentStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.SHIPMENTS.SHIPMENT_STATUS</code>.
     */
    public String getShipmentStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShipmentsRecord
     */
    public ShipmentsRecord() {
        super(Shipments.SHIPMENTS);
    }

    /**
     * Create a detached, initialised ShipmentsRecord
     */
    public ShipmentsRecord(Long shipmentId, Long storeId, Long customerId, String deliveryAddress,
                           String shipmentStatus) {
        super(Shipments.SHIPMENTS);

        setShipmentId(shipmentId);
        setStoreId(storeId);
        setCustomerId(customerId);
        setDeliveryAddress(deliveryAddress);
        setShipmentStatus(shipmentStatus);
        resetTouchedOnNotNull();
    }
}
