/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.StoreOrders;
import org.jooq.impl.TableRecordImpl;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StoreOrdersRecord
        extends TableRecordImpl<StoreOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.STORE_ORDERS.TOTAL</code>.
     */
    public void setTotal(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.TOTAL</code>.
     */
    public String getTotal() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.STORE_NAME</code>.
     */
    public void setStoreName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.STORE_NAME</code>.
     */
    public String getStoreName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.LATITUDE</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.LATITUDE</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.LONGITUDE</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.LONGITUDE</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.ORDER_STATUS</code>.
     */
    public void setOrderStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.ORDER_STATUS</code>.
     */
    public String getOrderStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.ORDER_COUNT</code>.
     */
    public void setOrderCount(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.ORDER_COUNT</code>.
     */
    public BigDecimal getOrderCount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>CO.STORE_ORDERS.TOTAL_SALES</code>.
     */
    public void setTotalSales(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>CO.STORE_ORDERS.TOTAL_SALES</code>.
     */
    public BigDecimal getTotalSales() {
        return (BigDecimal) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreOrdersRecord
     */
    public StoreOrdersRecord() {
        super(StoreOrders.STORE_ORDERS);
    }

    /**
     * Create a detached, initialised StoreOrdersRecord
     */
    public StoreOrdersRecord(String total, String storeName, String address, BigDecimal latitude, BigDecimal longitude,
                             String orderStatus, BigDecimal orderCount, BigDecimal totalSales) {
        super(StoreOrders.STORE_ORDERS);

        setTotal(total);
        setStoreName(storeName);
        setAddress(address);
        setLatitude(latitude);
        setLongitude(longitude);
        setOrderStatus(orderStatus);
        setOrderCount(orderCount);
        setTotalSales(totalSales);
        resetTouchedOnNotNull();
    }
}
