/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.records;

import com.github.jinahya.oracle.sample.schemas.co.data.jooq.tables.Stores;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StoresRecord
        extends UpdatableRecordImpl<StoresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CO.STORES.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CO.STORES.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CO.STORES.STORE_NAME</code>.
     */
    public void setStoreName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CO.STORES.STORE_NAME</code>.
     */
    public String getStoreName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CO.STORES.WEB_ADDRESS</code>.
     */
    public void setWebAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CO.STORES.WEB_ADDRESS</code>.
     */
    public String getWebAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CO.STORES.PHYSICAL_ADDRESS</code>.
     */
    public void setPhysicalAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CO.STORES.PHYSICAL_ADDRESS</code>.
     */
    public String getPhysicalAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CO.STORES.LATITUDE</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>CO.STORES.LATITUDE</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>CO.STORES.LONGITUDE</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>CO.STORES.LONGITUDE</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>CO.STORES.LOGO</code>.
     */
    public void setLogo(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>CO.STORES.LOGO</code>.
     */
    public byte[] getLogo() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>CO.STORES.LOGO_MIME_TYPE</code>.
     */
    public void setLogoMimeType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CO.STORES.LOGO_MIME_TYPE</code>.
     */
    public String getLogoMimeType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CO.STORES.LOGO_FILENAME</code>.
     */
    public void setLogoFilename(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CO.STORES.LOGO_FILENAME</code>.
     */
    public String getLogoFilename() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CO.STORES.LOGO_CHARSET</code>.
     */
    public void setLogoCharset(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CO.STORES.LOGO_CHARSET</code>.
     */
    public String getLogoCharset() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CO.STORES.LOGO_LAST_UPDATED</code>.
     */
    public void setLogoLastUpdated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>CO.STORES.LOGO_LAST_UPDATED</code>.
     */
    public LocalDateTime getLogoLastUpdated() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoresRecord
     */
    public StoresRecord() {
        super(Stores.STORES);
    }

    /**
     * Create a detached, initialised StoresRecord
     */
    public StoresRecord(Long storeId, String storeName, String webAddress, String physicalAddress, BigDecimal latitude,
                        BigDecimal longitude, byte[] logo, String logoMimeType, String logoFilename, String logoCharset,
                        LocalDateTime logoLastUpdated) {
        super(Stores.STORES);

        setStoreId(storeId);
        setStoreName(storeName);
        setWebAddress(webAddress);
        setPhysicalAddress(physicalAddress);
        setLatitude(latitude);
        setLongitude(longitude);
        setLogo(logo);
        setLogoMimeType(logoMimeType);
        setLogoFilename(logoFilename);
        setLogoCharset(logoCharset);
        setLogoLastUpdated(logoLastUpdated);
        resetTouchedOnNotNull();
    }
}
