/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq;

import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Countries;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Departments;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.EmpDetailsView;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Employees;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.JobHistory;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Jobs;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Locations;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Regions;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Hr
        extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>HR</code>
     */
    public static final Hr HR = new Hr();

    /**
     * The table <code>HR.COUNTRIES</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>HR.DEPARTMENTS</code>.
     */
    public final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>HR.EMP_DETAILS_VIEW</code>.
     */
    public final EmpDetailsView EMP_DETAILS_VIEW = EmpDetailsView.EMP_DETAILS_VIEW;

    /**
     * The table <code>HR.EMPLOYEES</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>HR.JOB_HISTORY</code>.
     */
    public final JobHistory JOB_HISTORY = JobHistory.JOB_HISTORY;

    /**
     * The table <code>HR.JOBS</code>.
     */
    public final Jobs JOBS = Jobs.JOBS;

    /**
     * The table <code>HR.LOCATIONS</code>.
     */
    public final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>HR.REGIONS</code>.
     */
    public final Regions REGIONS = Regions.REGIONS;

    /**
     * No further instances allowed
     */
    private Hr() {
        super(DSL.name("HR"), null, DSL.comment(""));
    }

    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Countries.COUNTRIES,
                Departments.DEPARTMENTS,
                EmpDetailsView.EMP_DETAILS_VIEW,
                Employees.EMPLOYEES,
                JobHistory.JOB_HISTORY,
                Jobs.JOBS,
                Locations.LOCATIONS,
                Regions.REGIONS
        );
    }
}
