/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq;


import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Countries;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Departments;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.EmpDetailsView;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Employees;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.JobHistory;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Jobs;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Locations;
import com.github.jinahya.oracle.sample.schemas.persistence.hr.data.jooq.tables.Regions;


/**
 * Convenience access to all tables in HR.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>HR.COUNTRIES</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>HR.DEPARTMENTS</code>.
     */
    public static final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>HR.EMP_DETAILS_VIEW</code>.
     */
    public static final EmpDetailsView EMP_DETAILS_VIEW = EmpDetailsView.EMP_DETAILS_VIEW;

    /**
     * The table <code>HR.EMPLOYEES</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>HR.JOB_HISTORY</code>.
     */
    public static final JobHistory JOB_HISTORY = JobHistory.JOB_HISTORY;

    /**
     * The table <code>HR.JOBS</code>.
     */
    public static final Jobs JOBS = Jobs.JOBS;

    /**
     * The table <code>HR.LOCATIONS</code>.
     */
    public static final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>HR.REGIONS</code>.
     */
    public static final Regions REGIONS = Regions.REGIONS;
}
