/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.CalMonthSalesMvRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CalMonthSalesMv extends TableImpl<CalMonthSalesMvRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.CAL_MONTH_SALES_MV</code>
     */
    public static final CalMonthSalesMv CAL_MONTH_SALES_MV = new CalMonthSalesMv();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CalMonthSalesMvRecord> getRecordType() {
        return CalMonthSalesMvRecord.class;
    }

    /**
     * The column <code>SH.CAL_MONTH_SALES_MV.CALENDAR_MONTH_DESC</code>.
     */
    public final TableField<CalMonthSalesMvRecord, String> CALENDAR_MONTH_DESC = createField(DSL.name("CALENDAR_MONTH_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CAL_MONTH_SALES_MV.DOLLARS</code>.
     */
    public final TableField<CalMonthSalesMvRecord, BigDecimal> DOLLARS = createField(DSL.name("DOLLARS"), SQLDataType.NUMERIC, this, "");

    private CalMonthSalesMv(Name alias, Table<CalMonthSalesMvRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CalMonthSalesMv(Name alias, Table<CalMonthSalesMvRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.CAL_MONTH_SALES_MV</code> table reference
     */
    public CalMonthSalesMv(String alias) {
        this(DSL.name(alias), CAL_MONTH_SALES_MV);
    }

    /**
     * Create an aliased <code>SH.CAL_MONTH_SALES_MV</code> table reference
     */
    public CalMonthSalesMv(Name alias) {
        this(alias, CAL_MONTH_SALES_MV);
    }

    /**
     * Create a <code>SH.CAL_MONTH_SALES_MV</code> table reference
     */
    public CalMonthSalesMv() {
        this(DSL.name("CAL_MONTH_SALES_MV"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public CalMonthSalesMv as(String alias) {
        return new CalMonthSalesMv(DSL.name(alias), this);
    }

    @Override
    public CalMonthSalesMv as(Name alias) {
        return new CalMonthSalesMv(alias, this);
    }

    @Override
    public CalMonthSalesMv as(Table<?> alias) {
        return new CalMonthSalesMv(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CalMonthSalesMv rename(String name) {
        return new CalMonthSalesMv(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CalMonthSalesMv rename(Name name) {
        return new CalMonthSalesMv(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CalMonthSalesMv rename(Table<?> name) {
        return new CalMonthSalesMv(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CalMonthSalesMv where(Condition condition) {
        return new CalMonthSalesMv(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CalMonthSalesMv where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CalMonthSalesMv where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CalMonthSalesMv where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CalMonthSalesMv where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CalMonthSalesMv where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CalMonthSalesMv where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CalMonthSalesMv where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CalMonthSalesMv whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CalMonthSalesMv whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
