/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.ChannelsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Channels
        extends TableImpl<ChannelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.CHANNELS</code>
     */
    public static final Channels CHANNELS = new Channels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChannelsRecord> getRecordType() {
        return ChannelsRecord.class;
    }

    /**
     * The column <code>SH.CHANNELS.CHANNEL_ID</code>.
     */
    public final TableField<ChannelsRecord, Long> CHANNEL_ID =
            createField(DSL.name("CHANNEL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CHANNELS.CHANNEL_DESC</code>.
     */
    public final TableField<ChannelsRecord, String> CHANNEL_DESC =
            createField(DSL.name("CHANNEL_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CHANNELS.CHANNEL_CLASS</code>.
     */
    public final TableField<ChannelsRecord, String> CHANNEL_CLASS =
            createField(DSL.name("CHANNEL_CLASS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CHANNELS.CHANNEL_CLASS_ID</code>.
     */
    public final TableField<ChannelsRecord, Long> CHANNEL_CLASS_ID =
            createField(DSL.name("CHANNEL_CLASS_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CHANNELS.CHANNEL_TOTAL</code>.
     */
    public final TableField<ChannelsRecord, String> CHANNEL_TOTAL =
            createField(DSL.name("CHANNEL_TOTAL"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CHANNELS.CHANNEL_TOTAL_ID</code>.
     */
    public final TableField<ChannelsRecord, Long> CHANNEL_TOTAL_ID =
            createField(DSL.name("CHANNEL_TOTAL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Channels(Name alias, Table<ChannelsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Channels(Name alias, Table<ChannelsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.CHANNELS</code> table reference
     */
    public Channels(String alias) {
        this(DSL.name(alias), CHANNELS);
    }

    /**
     * Create an aliased <code>SH.CHANNELS</code> table reference
     */
    public Channels(Name alias) {
        this(alias, CHANNELS);
    }

    /**
     * Create a <code>SH.CHANNELS</code> table reference
     */
    public Channels() {
        this(DSL.name("CHANNELS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<ChannelsRecord> getPrimaryKey() {
        return Keys.PK_CHANNELS;
    }

    @Override
    public Channels as(String alias) {
        return new Channels(DSL.name(alias), this);
    }

    @Override
    public Channels as(Name alias) {
        return new Channels(alias, this);
    }

    @Override
    public Channels as(Table<?> alias) {
        return new Channels(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Channels rename(String name) {
        return new Channels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Channels rename(Name name) {
        return new Channels(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Channels rename(Table<?> name) {
        return new Channels(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Channels where(Condition condition) {
        return new Channels(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Channels where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Channels where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Channels where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Channels where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Channels where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Channels where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Channels where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Channels whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Channels whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
