/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.CostsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Costs extends TableImpl<CostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.COSTS</code>
     */
    public static final Costs COSTS = new Costs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CostsRecord> getRecordType() {
        return CostsRecord.class;
    }

    /**
     * The column <code>SH.COSTS.PROD_ID</code>.
     */
    public final TableField<CostsRecord, Long> PROD_ID = createField(DSL.name("PROD_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.COSTS.TIME_ID</code>.
     */
    public final TableField<CostsRecord, LocalDateTime> TIME_ID = createField(DSL.name("TIME_ID"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.COSTS.PROMO_ID</code>.
     */
    public final TableField<CostsRecord, Long> PROMO_ID = createField(DSL.name("PROMO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.COSTS.CHANNEL_ID</code>.
     */
    public final TableField<CostsRecord, Long> CHANNEL_ID = createField(DSL.name("CHANNEL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.COSTS.UNIT_COST</code>.
     */
    public final TableField<CostsRecord, BigDecimal> UNIT_COST = createField(DSL.name("UNIT_COST"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.COSTS.UNIT_PRICE</code>.
     */
    public final TableField<CostsRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("UNIT_PRICE"), SQLDataType.NUMERIC.nullable(false), this, "");

    private Costs(Name alias, Table<CostsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Costs(Name alias, Table<CostsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.COSTS</code> table reference
     */
    public Costs(String alias) {
        this(DSL.name(alias), COSTS);
    }

    /**
     * Create an aliased <code>SH.COSTS</code> table reference
     */
    public Costs(Name alias) {
        this(alias, COSTS);
    }

    /**
     * Create a <code>SH.COSTS</code> table reference
     */
    public Costs() {
        this(DSL.name("COSTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public Costs as(String alias) {
        return new Costs(DSL.name(alias), this);
    }

    @Override
    public Costs as(Name alias) {
        return new Costs(alias, this);
    }

    @Override
    public Costs as(Table<?> alias) {
        return new Costs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Costs rename(String name) {
        return new Costs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Costs rename(Name name) {
        return new Costs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Costs rename(Table<?> name) {
        return new Costs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Costs where(Condition condition) {
        return new Costs(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Costs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Costs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Costs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Costs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Costs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Costs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Costs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Costs whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Costs whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
