/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.CountriesRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Countries extends TableImpl<CountriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.COUNTRIES</code>
     */
    public static final Countries COUNTRIES = new Countries();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CountriesRecord> getRecordType() {
        return CountriesRecord.class;
    }

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_ID</code>.
     */
    public final TableField<CountriesRecord, Long> COUNTRY_ID = createField(DSL.name("COUNTRY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_ISO_CODE</code>.
     */
    public final TableField<CountriesRecord, String> COUNTRY_ISO_CODE = createField(DSL.name("COUNTRY_ISO_CODE"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_NAME</code>.
     */
    public final TableField<CountriesRecord, String> COUNTRY_NAME = createField(DSL.name("COUNTRY_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_SUBREGION</code>.
     */
    public final TableField<CountriesRecord, String> COUNTRY_SUBREGION = createField(DSL.name("COUNTRY_SUBREGION"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_SUBREGION_ID</code>.
     */
    public final TableField<CountriesRecord, Long> COUNTRY_SUBREGION_ID = createField(DSL.name("COUNTRY_SUBREGION_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_REGION</code>.
     */
    public final TableField<CountriesRecord, String> COUNTRY_REGION = createField(DSL.name("COUNTRY_REGION"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_REGION_ID</code>.
     */
    public final TableField<CountriesRecord, Long> COUNTRY_REGION_ID = createField(DSL.name("COUNTRY_REGION_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_TOTAL</code>.
     */
    public final TableField<CountriesRecord, String> COUNTRY_TOTAL = createField(DSL.name("COUNTRY_TOTAL"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.COUNTRIES.COUNTRY_TOTAL_ID</code>.
     */
    public final TableField<CountriesRecord, Long> COUNTRY_TOTAL_ID = createField(DSL.name("COUNTRY_TOTAL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Countries(Name alias, Table<CountriesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Countries(Name alias, Table<CountriesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.COUNTRIES</code> table reference
     */
    public Countries(String alias) {
        this(DSL.name(alias), COUNTRIES);
    }

    /**
     * Create an aliased <code>SH.COUNTRIES</code> table reference
     */
    public Countries(Name alias) {
        this(alias, COUNTRIES);
    }

    /**
     * Create a <code>SH.COUNTRIES</code> table reference
     */
    public Countries() {
        this(DSL.name("COUNTRIES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<CountriesRecord> getPrimaryKey() {
        return Keys.PK_COUNTRIES;
    }

    @Override
    public Countries as(String alias) {
        return new Countries(DSL.name(alias), this);
    }

    @Override
    public Countries as(Name alias) {
        return new Countries(alias, this);
    }

    @Override
    public Countries as(Table<?> alias) {
        return new Countries(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Countries rename(String name) {
        return new Countries(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Countries rename(Name name) {
        return new Countries(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Countries rename(Table<?> name) {
        return new Countries(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Countries where(Condition condition) {
        return new Countries(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Countries where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Countries where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Countries where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Countries where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Countries where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Countries where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Countries where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Countries whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Countries whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
