/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.CustomersRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Customers
        extends TableImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.CUSTOMERS</code>
     */
    public static final Customers CUSTOMERS = new Customers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomersRecord> getRecordType() {
        return CustomersRecord.class;
    }

    /**
     * The column <code>SH.CUSTOMERS.CUST_ID</code>.
     */
    public final TableField<CustomersRecord, Long> CUST_ID =
            createField(DSL.name("CUST_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_FIRST_NAME</code>.
     */
    public final TableField<CustomersRecord, String> CUST_FIRST_NAME =
            createField(DSL.name("CUST_FIRST_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_LAST_NAME</code>.
     */
    public final TableField<CustomersRecord, String> CUST_LAST_NAME =
            createField(DSL.name("CUST_LAST_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_GENDER</code>.
     */
    public final TableField<CustomersRecord, String> CUST_GENDER =
            createField(DSL.name("CUST_GENDER"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_YEAR_OF_BIRTH</code>.
     */
    public final TableField<CustomersRecord, BigDecimal> CUST_YEAR_OF_BIRTH =
            createField(DSL.name("CUST_YEAR_OF_BIRTH"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_MARITAL_STATUS</code>.
     */
    public final TableField<CustomersRecord, String> CUST_MARITAL_STATUS =
            createField(DSL.name("CUST_MARITAL_STATUS"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_STREET_ADDRESS</code>.
     */
    public final TableField<CustomersRecord, String> CUST_STREET_ADDRESS =
            createField(DSL.name("CUST_STREET_ADDRESS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_POSTAL_CODE</code>.
     */
    public final TableField<CustomersRecord, String> CUST_POSTAL_CODE =
            createField(DSL.name("CUST_POSTAL_CODE"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_CITY</code>.
     */
    public final TableField<CustomersRecord, String> CUST_CITY =
            createField(DSL.name("CUST_CITY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_CITY_ID</code>.
     */
    public final TableField<CustomersRecord, Long> CUST_CITY_ID =
            createField(DSL.name("CUST_CITY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_STATE_PROVINCE</code>.
     */
    public final TableField<CustomersRecord, String> CUST_STATE_PROVINCE =
            createField(DSL.name("CUST_STATE_PROVINCE"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_STATE_PROVINCE_ID</code>.
     */
    public final TableField<CustomersRecord, Long> CUST_STATE_PROVINCE_ID =
            createField(DSL.name("CUST_STATE_PROVINCE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.COUNTRY_ID</code>.
     */
    public final TableField<CustomersRecord, Long> COUNTRY_ID =
            createField(DSL.name("COUNTRY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_MAIN_PHONE_NUMBER</code>.
     */
    public final TableField<CustomersRecord, String> CUST_MAIN_PHONE_NUMBER =
            createField(DSL.name("CUST_MAIN_PHONE_NUMBER"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_INCOME_LEVEL</code>.
     */
    public final TableField<CustomersRecord, String> CUST_INCOME_LEVEL =
            createField(DSL.name("CUST_INCOME_LEVEL"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_CREDIT_LIMIT</code>.
     */
    public final TableField<CustomersRecord, BigDecimal> CUST_CREDIT_LIMIT =
            createField(DSL.name("CUST_CREDIT_LIMIT"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_EMAIL</code>.
     */
    public final TableField<CustomersRecord, String> CUST_EMAIL =
            createField(DSL.name("CUST_EMAIL"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_TOTAL</code>.
     */
    public final TableField<CustomersRecord, String> CUST_TOTAL =
            createField(DSL.name("CUST_TOTAL"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_TOTAL_ID</code>.
     */
    public final TableField<CustomersRecord, Long> CUST_TOTAL_ID =
            createField(DSL.name("CUST_TOTAL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_SRC_ID</code>.
     */
    public final TableField<CustomersRecord, Long> CUST_SRC_ID =
            createField(DSL.name("CUST_SRC_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_EFF_FROM</code>.
     */
    public final TableField<CustomersRecord, LocalDateTime> CUST_EFF_FROM =
            createField(DSL.name("CUST_EFF_FROM"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_EFF_TO</code>.
     */
    public final TableField<CustomersRecord, LocalDateTime> CUST_EFF_TO =
            createField(DSL.name("CUST_EFF_TO"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>SH.CUSTOMERS.CUST_VALID</code>.
     */
    public final TableField<CustomersRecord, String> CUST_VALID =
            createField(DSL.name("CUST_VALID"), SQLDataType.VARCHAR, this, "");

    private Customers(Name alias, Table<CustomersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.CUSTOMERS</code> table reference
     */
    public Customers(String alias) {
        this(DSL.name(alias), CUSTOMERS);
    }

    /**
     * Create an aliased <code>SH.CUSTOMERS</code> table reference
     */
    public Customers(Name alias) {
        this(alias, CUSTOMERS);
    }

    /**
     * Create a <code>SH.CUSTOMERS</code> table reference
     */
    public Customers() {
        this(DSL.name("CUSTOMERS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<CustomersRecord> getPrimaryKey() {
        return Keys.PK_CUSTOMERS;
    }

    @Override
    public Customers as(String alias) {
        return new Customers(DSL.name(alias), this);
    }

    @Override
    public Customers as(Name alias) {
        return new Customers(alias, this);
    }

    @Override
    public Customers as(Table<?> alias) {
        return new Customers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(String name) {
        return new Customers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Name name) {
        return new Customers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Table<?> name) {
        return new Customers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Condition condition) {
        return new Customers(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
