/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.FweekPscatSalesMvRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class FweekPscatSalesMv
        extends TableImpl<FweekPscatSalesMvRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.FWEEK_PSCAT_SALES_MV</code>
     */
    public static final FweekPscatSalesMv FWEEK_PSCAT_SALES_MV = new FweekPscatSalesMv();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FweekPscatSalesMvRecord> getRecordType() {
        return FweekPscatSalesMvRecord.class;
    }

    /**
     * The column <code>SH.FWEEK_PSCAT_SALES_MV.WEEK_ENDING_DAY</code>.
     */
    public final TableField<FweekPscatSalesMvRecord, LocalDateTime> WEEK_ENDING_DAY =
            createField(DSL.name("WEEK_ENDING_DAY"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.FWEEK_PSCAT_SALES_MV.PROD_SUBCATEGORY</code>.
     */
    public final TableField<FweekPscatSalesMvRecord, String> PROD_SUBCATEGORY =
            createField(DSL.name("PROD_SUBCATEGORY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.FWEEK_PSCAT_SALES_MV.DOLLARS</code>.
     */
    public final TableField<FweekPscatSalesMvRecord, BigDecimal> DOLLARS =
            createField(DSL.name("DOLLARS"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.FWEEK_PSCAT_SALES_MV.CHANNEL_ID</code>.
     */
    public final TableField<FweekPscatSalesMvRecord, Long> CHANNEL_ID =
            createField(DSL.name("CHANNEL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.FWEEK_PSCAT_SALES_MV.PROMO_ID</code>.
     */
    public final TableField<FweekPscatSalesMvRecord, Long> PROMO_ID =
            createField(DSL.name("PROMO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private FweekPscatSalesMv(Name alias, Table<FweekPscatSalesMvRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FweekPscatSalesMv(Name alias, Table<FweekPscatSalesMvRecord> aliased, Field<?>[] parameters,
                              Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.FWEEK_PSCAT_SALES_MV</code> table reference
     */
    public FweekPscatSalesMv(String alias) {
        this(DSL.name(alias), FWEEK_PSCAT_SALES_MV);
    }

    /**
     * Create an aliased <code>SH.FWEEK_PSCAT_SALES_MV</code> table reference
     */
    public FweekPscatSalesMv(Name alias) {
        this(alias, FWEEK_PSCAT_SALES_MV);
    }

    /**
     * Create a <code>SH.FWEEK_PSCAT_SALES_MV</code> table reference
     */
    public FweekPscatSalesMv() {
        this(DSL.name("FWEEK_PSCAT_SALES_MV"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public FweekPscatSalesMv as(String alias) {
        return new FweekPscatSalesMv(DSL.name(alias), this);
    }

    @Override
    public FweekPscatSalesMv as(Name alias) {
        return new FweekPscatSalesMv(alias, this);
    }

    @Override
    public FweekPscatSalesMv as(Table<?> alias) {
        return new FweekPscatSalesMv(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FweekPscatSalesMv rename(String name) {
        return new FweekPscatSalesMv(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FweekPscatSalesMv rename(Name name) {
        return new FweekPscatSalesMv(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FweekPscatSalesMv rename(Table<?> name) {
        return new FweekPscatSalesMv(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FweekPscatSalesMv where(Condition condition) {
        return new FweekPscatSalesMv(getQualifiedName(), aliased() ? this : null, null,
                                     Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FweekPscatSalesMv where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FweekPscatSalesMv where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FweekPscatSalesMv where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FweekPscatSalesMv where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FweekPscatSalesMv where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FweekPscatSalesMv where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FweekPscatSalesMv where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FweekPscatSalesMv whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FweekPscatSalesMv whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
