/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.ProductsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Products extends TableImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.PRODUCTS</code>
     */
    public static final Products PRODUCTS = new Products();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductsRecord> getRecordType() {
        return ProductsRecord.class;
    }

    /**
     * The column <code>SH.PRODUCTS.PROD_ID</code>.
     */
    public final TableField<ProductsRecord, Long> PROD_ID = createField(DSL.name("PROD_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_NAME</code>.
     */
    public final TableField<ProductsRecord, String> PROD_NAME = createField(DSL.name("PROD_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_DESC</code>.
     */
    public final TableField<ProductsRecord, String> PROD_DESC = createField(DSL.name("PROD_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_SUBCATEGORY</code>.
     */
    public final TableField<ProductsRecord, String> PROD_SUBCATEGORY = createField(DSL.name("PROD_SUBCATEGORY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_SUBCATEGORY_ID</code>.
     */
    public final TableField<ProductsRecord, Long> PROD_SUBCATEGORY_ID = createField(DSL.name("PROD_SUBCATEGORY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_SUBCATEGORY_DESC</code>.
     */
    public final TableField<ProductsRecord, String> PROD_SUBCATEGORY_DESC = createField(DSL.name("PROD_SUBCATEGORY_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_CATEGORY</code>.
     */
    public final TableField<ProductsRecord, String> PROD_CATEGORY = createField(DSL.name("PROD_CATEGORY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_CATEGORY_ID</code>.
     */
    public final TableField<ProductsRecord, Long> PROD_CATEGORY_ID = createField(DSL.name("PROD_CATEGORY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_CATEGORY_DESC</code>.
     */
    public final TableField<ProductsRecord, String> PROD_CATEGORY_DESC = createField(DSL.name("PROD_CATEGORY_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_WEIGHT_CLASS</code>.
     */
    public final TableField<ProductsRecord, BigDecimal> PROD_WEIGHT_CLASS = createField(DSL.name("PROD_WEIGHT_CLASS"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_UNIT_OF_MEASURE</code>.
     */
    public final TableField<ProductsRecord, String> PROD_UNIT_OF_MEASURE = createField(DSL.name("PROD_UNIT_OF_MEASURE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_PACK_SIZE</code>.
     */
    public final TableField<ProductsRecord, String> PROD_PACK_SIZE = createField(DSL.name("PROD_PACK_SIZE"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.SUPPLIER_ID</code>.
     */
    public final TableField<ProductsRecord, Long> SUPPLIER_ID = createField(DSL.name("SUPPLIER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_STATUS</code>.
     */
    public final TableField<ProductsRecord, String> PROD_STATUS = createField(DSL.name("PROD_STATUS"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_LIST_PRICE</code>.
     */
    public final TableField<ProductsRecord, BigDecimal> PROD_LIST_PRICE = createField(DSL.name("PROD_LIST_PRICE"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_MIN_PRICE</code>.
     */
    public final TableField<ProductsRecord, BigDecimal> PROD_MIN_PRICE = createField(DSL.name("PROD_MIN_PRICE"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_TOTAL</code>.
     */
    public final TableField<ProductsRecord, String> PROD_TOTAL = createField(DSL.name("PROD_TOTAL"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_TOTAL_ID</code>.
     */
    public final TableField<ProductsRecord, Long> PROD_TOTAL_ID = createField(DSL.name("PROD_TOTAL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_SRC_ID</code>.
     */
    public final TableField<ProductsRecord, Long> PROD_SRC_ID = createField(DSL.name("PROD_SRC_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_EFF_FROM</code>.
     */
    public final TableField<ProductsRecord, LocalDateTime> PROD_EFF_FROM = createField(DSL.name("PROD_EFF_FROM"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_EFF_TO</code>.
     */
    public final TableField<ProductsRecord, LocalDateTime> PROD_EFF_TO = createField(DSL.name("PROD_EFF_TO"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>SH.PRODUCTS.PROD_VALID</code>.
     */
    public final TableField<ProductsRecord, String> PROD_VALID = createField(DSL.name("PROD_VALID"), SQLDataType.VARCHAR, this, "");

    private Products(Name alias, Table<ProductsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Products(Name alias, Table<ProductsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.PRODUCTS</code> table reference
     */
    public Products(String alias) {
        this(DSL.name(alias), PRODUCTS);
    }

    /**
     * Create an aliased <code>SH.PRODUCTS</code> table reference
     */
    public Products(Name alias) {
        this(alias, PRODUCTS);
    }

    /**
     * Create a <code>SH.PRODUCTS</code> table reference
     */
    public Products() {
        this(DSL.name("PRODUCTS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<ProductsRecord> getPrimaryKey() {
        return Keys.PK_PRODUCTS;
    }

    @Override
    public Products as(String alias) {
        return new Products(DSL.name(alias), this);
    }

    @Override
    public Products as(Name alias) {
        return new Products(alias, this);
    }

    @Override
    public Products as(Table<?> alias) {
        return new Products(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(String name) {
        return new Products(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Name name) {
        return new Products(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Table<?> name) {
        return new Products(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Condition condition) {
        return new Products(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Products where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Products whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
