/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.ProfitsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Profits
        extends TableImpl<ProfitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.PROFITS</code>
     */
    public static final Profits PROFITS = new Profits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfitsRecord> getRecordType() {
        return ProfitsRecord.class;
    }

    /**
     * The column <code>SH.PROFITS.CHANNEL_ID</code>.
     */
    public final TableField<ProfitsRecord, Long> CHANNEL_ID =
            createField(DSL.name("CHANNEL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.CUST_ID</code>.
     */
    public final TableField<ProfitsRecord, Long> CUST_ID =
            createField(DSL.name("CUST_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.PROD_ID</code>.
     */
    public final TableField<ProfitsRecord, Long> PROD_ID =
            createField(DSL.name("PROD_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.PROMO_ID</code>.
     */
    public final TableField<ProfitsRecord, Long> PROMO_ID =
            createField(DSL.name("PROMO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.TIME_ID</code>.
     */
    public final TableField<ProfitsRecord, LocalDateTime> TIME_ID =
            createField(DSL.name("TIME_ID"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.UNIT_COST</code>.
     */
    public final TableField<ProfitsRecord, BigDecimal> UNIT_COST =
            createField(DSL.name("UNIT_COST"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.UNIT_PRICE</code>.
     */
    public final TableField<ProfitsRecord, BigDecimal> UNIT_PRICE =
            createField(DSL.name("UNIT_PRICE"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.AMOUNT_SOLD</code>.
     */
    public final TableField<ProfitsRecord, BigDecimal> AMOUNT_SOLD =
            createField(DSL.name("AMOUNT_SOLD"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.QUANTITY_SOLD</code>.
     */
    public final TableField<ProfitsRecord, BigDecimal> QUANTITY_SOLD =
            createField(DSL.name("QUANTITY_SOLD"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PROFITS.TOTAL_COST</code>.
     */
    public final TableField<ProfitsRecord, BigDecimal> TOTAL_COST =
            createField(DSL.name("TOTAL_COST"), SQLDataType.NUMERIC, this, "");

    private Profits(Name alias, Table<ProfitsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Profits(Name alias, Table<ProfitsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view(), where);
    }

    /**
     * Create an aliased <code>SH.PROFITS</code> table reference
     */
    public Profits(String alias) {
        this(DSL.name(alias), PROFITS);
    }

    /**
     * Create an aliased <code>SH.PROFITS</code> table reference
     */
    public Profits(Name alias) {
        this(alias, PROFITS);
    }

    /**
     * Create a <code>SH.PROFITS</code> table reference
     */
    public Profits() {
        this(DSL.name("PROFITS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public Profits as(String alias) {
        return new Profits(DSL.name(alias), this);
    }

    @Override
    public Profits as(Name alias) {
        return new Profits(alias, this);
    }

    @Override
    public Profits as(Table<?> alias) {
        return new Profits(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Profits rename(String name) {
        return new Profits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profits rename(Name name) {
        return new Profits(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Profits rename(Table<?> name) {
        return new Profits(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profits where(Condition condition) {
        return new Profits(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profits where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profits where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profits where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profits where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profits where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profits where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Profits where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profits whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Profits whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
