/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.PromotionsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Promotions extends TableImpl<PromotionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.PROMOTIONS</code>
     */
    public static final Promotions PROMOTIONS = new Promotions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PromotionsRecord> getRecordType() {
        return PromotionsRecord.class;
    }

    /**
     * The column <code>SH.PROMOTIONS.PROMO_ID</code>.
     */
    public final TableField<PromotionsRecord, Long> PROMO_ID = createField(DSL.name("PROMO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_NAME</code>.
     */
    public final TableField<PromotionsRecord, String> PROMO_NAME = createField(DSL.name("PROMO_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_SUBCATEGORY</code>.
     */
    public final TableField<PromotionsRecord, String> PROMO_SUBCATEGORY = createField(DSL.name("PROMO_SUBCATEGORY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_SUBCATEGORY_ID</code>.
     */
    public final TableField<PromotionsRecord, Long> PROMO_SUBCATEGORY_ID = createField(DSL.name("PROMO_SUBCATEGORY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_CATEGORY</code>.
     */
    public final TableField<PromotionsRecord, String> PROMO_CATEGORY = createField(DSL.name("PROMO_CATEGORY"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_CATEGORY_ID</code>.
     */
    public final TableField<PromotionsRecord, Long> PROMO_CATEGORY_ID = createField(DSL.name("PROMO_CATEGORY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_COST</code>.
     */
    public final TableField<PromotionsRecord, BigDecimal> PROMO_COST = createField(DSL.name("PROMO_COST"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_BEGIN_DATE</code>.
     */
    public final TableField<PromotionsRecord, LocalDateTime> PROMO_BEGIN_DATE = createField(DSL.name("PROMO_BEGIN_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_END_DATE</code>.
     */
    public final TableField<PromotionsRecord, LocalDateTime> PROMO_END_DATE = createField(DSL.name("PROMO_END_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_TOTAL</code>.
     */
    public final TableField<PromotionsRecord, String> PROMO_TOTAL = createField(DSL.name("PROMO_TOTAL"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.PROMOTIONS.PROMO_TOTAL_ID</code>.
     */
    public final TableField<PromotionsRecord, Long> PROMO_TOTAL_ID = createField(DSL.name("PROMO_TOTAL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Promotions(Name alias, Table<PromotionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Promotions(Name alias, Table<PromotionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.PROMOTIONS</code> table reference
     */
    public Promotions(String alias) {
        this(DSL.name(alias), PROMOTIONS);
    }

    /**
     * Create an aliased <code>SH.PROMOTIONS</code> table reference
     */
    public Promotions(Name alias) {
        this(alias, PROMOTIONS);
    }

    /**
     * Create a <code>SH.PROMOTIONS</code> table reference
     */
    public Promotions() {
        this(DSL.name("PROMOTIONS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<PromotionsRecord> getPrimaryKey() {
        return Keys.PK_PROMOTIONS;
    }

    @Override
    public Promotions as(String alias) {
        return new Promotions(DSL.name(alias), this);
    }

    @Override
    public Promotions as(Name alias) {
        return new Promotions(alias, this);
    }

    @Override
    public Promotions as(Table<?> alias) {
        return new Promotions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Promotions rename(String name) {
        return new Promotions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Promotions rename(Name name) {
        return new Promotions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Promotions rename(Table<?> name) {
        return new Promotions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Promotions where(Condition condition) {
        return new Promotions(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Promotions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Promotions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Promotions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Promotions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Promotions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Promotions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Promotions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Promotions whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Promotions whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
