/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.SalesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Sales
        extends TableImpl<SalesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.SALES</code>
     */
    public static final Sales SALES = new Sales();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesRecord> getRecordType() {
        return SalesRecord.class;
    }

    /**
     * The column <code>SH.SALES.PROD_ID</code>.
     */
    public final TableField<SalesRecord, Long> PROD_ID =
            createField(DSL.name("PROD_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.SALES.CUST_ID</code>.
     */
    public final TableField<SalesRecord, Long> CUST_ID =
            createField(DSL.name("CUST_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.SALES.TIME_ID</code>.
     */
    public final TableField<SalesRecord, LocalDateTime> TIME_ID =
            createField(DSL.name("TIME_ID"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.SALES.CHANNEL_ID</code>.
     */
    public final TableField<SalesRecord, Long> CHANNEL_ID =
            createField(DSL.name("CHANNEL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.SALES.PROMO_ID</code>.
     */
    public final TableField<SalesRecord, Long> PROMO_ID =
            createField(DSL.name("PROMO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.SALES.QUANTITY_SOLD</code>.
     */
    public final TableField<SalesRecord, BigDecimal> QUANTITY_SOLD =
            createField(DSL.name("QUANTITY_SOLD"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.SALES.AMOUNT_SOLD</code>.
     */
    public final TableField<SalesRecord, BigDecimal> AMOUNT_SOLD =
            createField(DSL.name("AMOUNT_SOLD"), SQLDataType.NUMERIC.nullable(false), this, "");

    private Sales(Name alias, Table<SalesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sales(Name alias, Table<SalesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.SALES</code> table reference
     */
    public Sales(String alias) {
        this(DSL.name(alias), SALES);
    }

    /**
     * Create an aliased <code>SH.SALES</code> table reference
     */
    public Sales(Name alias) {
        this(alias, SALES);
    }

    /**
     * Create a <code>SH.SALES</code> table reference
     */
    public Sales() {
        this(DSL.name("SALES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public Sales as(String alias) {
        return new Sales(DSL.name(alias), this);
    }

    @Override
    public Sales as(Name alias) {
        return new Sales(alias, this);
    }

    @Override
    public Sales as(Table<?> alias) {
        return new Sales(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sales rename(String name) {
        return new Sales(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sales rename(Name name) {
        return new Sales(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sales rename(Table<?> name) {
        return new Sales(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Condition condition) {
        return new Sales(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sales where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sales whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
