/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.SupplementaryDemographicsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class SupplementaryDemographics
        extends TableImpl<SupplementaryDemographicsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.SUPPLEMENTARY_DEMOGRAPHICS</code>
     */
    public static final SupplementaryDemographics SUPPLEMENTARY_DEMOGRAPHICS = new SupplementaryDemographics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplementaryDemographicsRecord> getRecordType() {
        return SupplementaryDemographicsRecord.class;
    }

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.CUST_ID</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, Long> CUST_ID =
            createField(DSL.name("CUST_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.EDUCATION</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, String> EDUCATION =
            createField(DSL.name("EDUCATION"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.OCCUPATION</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, String> OCCUPATION =
            createField(DSL.name("OCCUPATION"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.HOUSEHOLD_SIZE</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, String> HOUSEHOLD_SIZE =
            createField(DSL.name("HOUSEHOLD_SIZE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.YRS_RESIDENCE</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> YRS_RESIDENCE =
            createField(DSL.name("YRS_RESIDENCE"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.AFFINITY_CARD</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> AFFINITY_CARD =
            createField(DSL.name("AFFINITY_CARD"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.CRICKET</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> CRICKET =
            createField(DSL.name("CRICKET"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.BASEBALL</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> BASEBALL =
            createField(DSL.name("BASEBALL"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.TENNIS</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> TENNIS =
            createField(DSL.name("TENNIS"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.SOCCER</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> SOCCER =
            createField(DSL.name("SOCCER"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.GOLF</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> GOLF =
            createField(DSL.name("GOLF"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.UNKNOWN</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> UNKNOWN =
            createField(DSL.name("UNKNOWN"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.MISC</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, BigDecimal> MISC =
            createField(DSL.name("MISC"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>SH.SUPPLEMENTARY_DEMOGRAPHICS.COMMENTS</code>.
     */
    public final TableField<SupplementaryDemographicsRecord, String> COMMENTS =
            createField(DSL.name("COMMENTS"), SQLDataType.VARCHAR, this, "");

    private SupplementaryDemographics(Name alias, Table<SupplementaryDemographicsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SupplementaryDemographics(Name alias, Table<SupplementaryDemographicsRecord> aliased, Field<?>[] parameters,
                                      Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.SUPPLEMENTARY_DEMOGRAPHICS</code> table reference
     */
    public SupplementaryDemographics(String alias) {
        this(DSL.name(alias), SUPPLEMENTARY_DEMOGRAPHICS);
    }

    /**
     * Create an aliased <code>SH.SUPPLEMENTARY_DEMOGRAPHICS</code> table reference
     */
    public SupplementaryDemographics(Name alias) {
        this(alias, SUPPLEMENTARY_DEMOGRAPHICS);
    }

    /**
     * Create a <code>SH.SUPPLEMENTARY_DEMOGRAPHICS</code> table reference
     */
    public SupplementaryDemographics() {
        this(DSL.name("SUPPLEMENTARY_DEMOGRAPHICS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<SupplementaryDemographicsRecord> getPrimaryKey() {
        return Keys.PK_SUPPLEMENTARY_DEMOGRAPHICS;
    }

    @Override
    public SupplementaryDemographics as(String alias) {
        return new SupplementaryDemographics(DSL.name(alias), this);
    }

    @Override
    public SupplementaryDemographics as(Name alias) {
        return new SupplementaryDemographics(alias, this);
    }

    @Override
    public SupplementaryDemographics as(Table<?> alias) {
        return new SupplementaryDemographics(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplementaryDemographics rename(String name) {
        return new SupplementaryDemographics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplementaryDemographics rename(Name name) {
        return new SupplementaryDemographics(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplementaryDemographics rename(Table<?> name) {
        return new SupplementaryDemographics(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupplementaryDemographics where(Condition condition) {
        return new SupplementaryDemographics(getQualifiedName(), aliased() ? this : null, null,
                                             Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupplementaryDemographics where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupplementaryDemographics where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupplementaryDemographics where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupplementaryDemographics where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupplementaryDemographics where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupplementaryDemographics where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupplementaryDemographics where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupplementaryDemographics whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupplementaryDemographics whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
