/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Keys;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.Sh;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.TimesRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Times extends TableImpl<TimesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH.TIMES</code>
     */
    public static final Times TIMES = new Times();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TimesRecord> getRecordType() {
        return TimesRecord.class;
    }

    /**
     * The column <code>SH.TIMES.TIME_ID</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> TIME_ID = createField(DSL.name("TIME_ID"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAY_NAME</code>.
     */
    public final TableField<TimesRecord, String> DAY_NAME = createField(DSL.name("DAY_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAY_NUMBER_IN_WEEK</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAY_NUMBER_IN_WEEK = createField(DSL.name("DAY_NUMBER_IN_WEEK"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAY_NUMBER_IN_MONTH</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAY_NUMBER_IN_MONTH = createField(DSL.name("DAY_NUMBER_IN_MONTH"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_WEEK_NUMBER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> CALENDAR_WEEK_NUMBER = createField(DSL.name("CALENDAR_WEEK_NUMBER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_WEEK_NUMBER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> FISCAL_WEEK_NUMBER = createField(DSL.name("FISCAL_WEEK_NUMBER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.WEEK_ENDING_DAY</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> WEEK_ENDING_DAY = createField(DSL.name("WEEK_ENDING_DAY"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.WEEK_ENDING_DAY_ID</code>.
     */
    public final TableField<TimesRecord, Long> WEEK_ENDING_DAY_ID = createField(DSL.name("WEEK_ENDING_DAY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_MONTH_NUMBER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> CALENDAR_MONTH_NUMBER = createField(DSL.name("CALENDAR_MONTH_NUMBER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_MONTH_NUMBER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> FISCAL_MONTH_NUMBER = createField(DSL.name("FISCAL_MONTH_NUMBER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_MONTH_DESC</code>.
     */
    public final TableField<TimesRecord, String> CALENDAR_MONTH_DESC = createField(DSL.name("CALENDAR_MONTH_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_MONTH_ID</code>.
     */
    public final TableField<TimesRecord, Long> CALENDAR_MONTH_ID = createField(DSL.name("CALENDAR_MONTH_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_MONTH_DESC</code>.
     */
    public final TableField<TimesRecord, String> FISCAL_MONTH_DESC = createField(DSL.name("FISCAL_MONTH_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_MONTH_ID</code>.
     */
    public final TableField<TimesRecord, Long> FISCAL_MONTH_ID = createField(DSL.name("FISCAL_MONTH_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAYS_IN_CAL_MONTH</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAYS_IN_CAL_MONTH = createField(DSL.name("DAYS_IN_CAL_MONTH"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAYS_IN_FIS_MONTH</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAYS_IN_FIS_MONTH = createField(DSL.name("DAYS_IN_FIS_MONTH"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.END_OF_CAL_MONTH</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> END_OF_CAL_MONTH = createField(DSL.name("END_OF_CAL_MONTH"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.END_OF_FIS_MONTH</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> END_OF_FIS_MONTH = createField(DSL.name("END_OF_FIS_MONTH"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_MONTH_NAME</code>.
     */
    public final TableField<TimesRecord, String> CALENDAR_MONTH_NAME = createField(DSL.name("CALENDAR_MONTH_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_MONTH_NAME</code>.
     */
    public final TableField<TimesRecord, String> FISCAL_MONTH_NAME = createField(DSL.name("FISCAL_MONTH_NAME"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_QUARTER_DESC</code>.
     */
    public final TableField<TimesRecord, String> CALENDAR_QUARTER_DESC = createField(DSL.name("CALENDAR_QUARTER_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_QUARTER_ID</code>.
     */
    public final TableField<TimesRecord, Long> CALENDAR_QUARTER_ID = createField(DSL.name("CALENDAR_QUARTER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_QUARTER_DESC</code>.
     */
    public final TableField<TimesRecord, String> FISCAL_QUARTER_DESC = createField(DSL.name("FISCAL_QUARTER_DESC"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_QUARTER_ID</code>.
     */
    public final TableField<TimesRecord, Long> FISCAL_QUARTER_ID = createField(DSL.name("FISCAL_QUARTER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAYS_IN_CAL_QUARTER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAYS_IN_CAL_QUARTER = createField(DSL.name("DAYS_IN_CAL_QUARTER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAYS_IN_FIS_QUARTER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAYS_IN_FIS_QUARTER = createField(DSL.name("DAYS_IN_FIS_QUARTER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.END_OF_CAL_QUARTER</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> END_OF_CAL_QUARTER = createField(DSL.name("END_OF_CAL_QUARTER"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.END_OF_FIS_QUARTER</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> END_OF_FIS_QUARTER = createField(DSL.name("END_OF_FIS_QUARTER"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_QUARTER_NUMBER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> CALENDAR_QUARTER_NUMBER = createField(DSL.name("CALENDAR_QUARTER_NUMBER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_QUARTER_NUMBER</code>.
     */
    public final TableField<TimesRecord, BigDecimal> FISCAL_QUARTER_NUMBER = createField(DSL.name("FISCAL_QUARTER_NUMBER"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_YEAR</code>.
     */
    public final TableField<TimesRecord, BigDecimal> CALENDAR_YEAR = createField(DSL.name("CALENDAR_YEAR"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.CALENDAR_YEAR_ID</code>.
     */
    public final TableField<TimesRecord, Long> CALENDAR_YEAR_ID = createField(DSL.name("CALENDAR_YEAR_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_YEAR</code>.
     */
    public final TableField<TimesRecord, BigDecimal> FISCAL_YEAR = createField(DSL.name("FISCAL_YEAR"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.FISCAL_YEAR_ID</code>.
     */
    public final TableField<TimesRecord, Long> FISCAL_YEAR_ID = createField(DSL.name("FISCAL_YEAR_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAYS_IN_CAL_YEAR</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAYS_IN_CAL_YEAR = createField(DSL.name("DAYS_IN_CAL_YEAR"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.DAYS_IN_FIS_YEAR</code>.
     */
    public final TableField<TimesRecord, BigDecimal> DAYS_IN_FIS_YEAR = createField(DSL.name("DAYS_IN_FIS_YEAR"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.END_OF_CAL_YEAR</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> END_OF_CAL_YEAR = createField(DSL.name("END_OF_CAL_YEAR"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>SH.TIMES.END_OF_FIS_YEAR</code>.
     */
    public final TableField<TimesRecord, LocalDateTime> END_OF_FIS_YEAR = createField(DSL.name("END_OF_FIS_YEAR"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private Times(Name alias, Table<TimesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Times(Name alias, Table<TimesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SH.TIMES</code> table reference
     */
    public Times(String alias) {
        this(DSL.name(alias), TIMES);
    }

    /**
     * Create an aliased <code>SH.TIMES</code> table reference
     */
    public Times(Name alias) {
        this(alias, TIMES);
    }

    /**
     * Create a <code>SH.TIMES</code> table reference
     */
    public Times() {
        this(DSL.name("TIMES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sh.SH;
    }

    @Override
    public UniqueKey<TimesRecord> getPrimaryKey() {
        return Keys.PK_TIMES;
    }

    @Override
    public Times as(String alias) {
        return new Times(DSL.name(alias), this);
    }

    @Override
    public Times as(Name alias) {
        return new Times(alias, this);
    }

    @Override
    public Times as(Table<?> alias) {
        return new Times(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Times rename(String name) {
        return new Times(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Times rename(Name name) {
        return new Times(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Times rename(Table<?> name) {
        return new Times(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Times where(Condition condition) {
        return new Times(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Times where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Times where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Times where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Times where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Times where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Times where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Times where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Times whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Times whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
