/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Channels;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Countries;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Customers;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Products;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Promotions;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.SupplementaryDemographics;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Times;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.ChannelsRecord;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.CountriesRecord;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.CustomersRecord;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.ProductsRecord;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.PromotionsRecord;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.SupplementaryDemographicsRecord;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.records.TimesRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in SH.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChannelsRecord> PK_CHANNELS = Internal.createUniqueKey(Channels.CHANNELS, DSL.name("PK_CHANNELS"), new TableField[] { Channels.CHANNELS.CHANNEL_ID }, true);
    public static final UniqueKey<CountriesRecord> PK_COUNTRIES = Internal.createUniqueKey(Countries.COUNTRIES, DSL.name("PK_COUNTRIES"), new TableField[] { Countries.COUNTRIES.COUNTRY_ID }, true);
    public static final UniqueKey<CustomersRecord> PK_CUSTOMERS = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("PK_CUSTOMERS"), new TableField[] { Customers.CUSTOMERS.CUST_ID }, true);
    public static final UniqueKey<ProductsRecord> PK_PRODUCTS = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("PK_PRODUCTS"), new TableField[] { Products.PRODUCTS.PROD_ID }, true);
    public static final UniqueKey<PromotionsRecord> PK_PROMOTIONS = Internal.createUniqueKey(Promotions.PROMOTIONS, DSL.name("PK_PROMOTIONS"), new TableField[] { Promotions.PROMOTIONS.PROMO_ID }, true);
    public static final UniqueKey<SupplementaryDemographicsRecord> PK_SUPPLEMENTARY_DEMOGRAPHICS = Internal.createUniqueKey(SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS, DSL.name("PK_SUPPLEMENTARY_DEMOGRAPHICS"), new TableField[] { SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS.CUST_ID }, true);
    public static final UniqueKey<TimesRecord> PK_TIMES = Internal.createUniqueKey(Times.TIMES, DSL.name("PK_TIMES"), new TableField[] { Times.TIMES.TIME_ID }, true);
}
