/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq;


import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.CalMonthSalesMv;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Channels;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Costs;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Countries;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Customers;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.FweekPscatSalesMv;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Products;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Profits;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Promotions;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Sales;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.SupplementaryDemographics;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Times;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sh extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SH</code>
     */
    public static final Sh SH = new Sh();

    /**
     * The table <code>SH.CAL_MONTH_SALES_MV</code>.
     */
    public final CalMonthSalesMv CAL_MONTH_SALES_MV = CalMonthSalesMv.CAL_MONTH_SALES_MV;

    /**
     * The table <code>SH.CHANNELS</code>.
     */
    public final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>SH.COSTS</code>.
     */
    public final Costs COSTS = Costs.COSTS;

    /**
     * The table <code>SH.COUNTRIES</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>SH.CUSTOMERS</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>SH.FWEEK_PSCAT_SALES_MV</code>.
     */
    public final FweekPscatSalesMv FWEEK_PSCAT_SALES_MV = FweekPscatSalesMv.FWEEK_PSCAT_SALES_MV;

    /**
     * The table <code>SH.PRODUCTS</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>SH.PROFITS</code>.
     */
    public final Profits PROFITS = Profits.PROFITS;

    /**
     * The table <code>SH.PROMOTIONS</code>.
     */
    public final Promotions PROMOTIONS = Promotions.PROMOTIONS;

    /**
     * The table <code>SH.SALES</code>.
     */
    public final Sales SALES = Sales.SALES;

    /**
     * The table <code>SH.SUPPLEMENTARY_DEMOGRAPHICS</code>.
     */
    public final SupplementaryDemographics SUPPLEMENTARY_DEMOGRAPHICS = SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS;

    /**
     * The table <code>SH.TIMES</code>.
     */
    public final Times TIMES = Times.TIMES;

    /**
     * No further instances allowed
     */
    private Sh() {
        super(DSL.name("SH"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CalMonthSalesMv.CAL_MONTH_SALES_MV,
            Channels.CHANNELS,
            Costs.COSTS,
            Countries.COUNTRIES,
            Customers.CUSTOMERS,
            FweekPscatSalesMv.FWEEK_PSCAT_SALES_MV,
            Products.PRODUCTS,
            Profits.PROFITS,
            Promotions.PROMOTIONS,
            Sales.SALES,
            SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS,
            Times.TIMES
        );
    }
}
