/*
 * This file is generated by jOOQ.
 */
package com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq;

import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.CalMonthSalesMv;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Channels;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Costs;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Countries;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Customers;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.FweekPscatSalesMv;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Products;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Profits;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Promotions;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Sales;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.SupplementaryDemographics;
import com.github.jinahya.oracle.sample.schemas.persistence.sh.data.jooq.tables.Times;

/**
 * Convenience access to all tables in SH.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>SH.CAL_MONTH_SALES_MV</code>.
     */
    public static final CalMonthSalesMv CAL_MONTH_SALES_MV = CalMonthSalesMv.CAL_MONTH_SALES_MV;

    /**
     * The table <code>SH.CHANNELS</code>.
     */
    public static final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>SH.COSTS</code>.
     */
    public static final Costs COSTS = Costs.COSTS;

    /**
     * The table <code>SH.COUNTRIES</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>SH.CUSTOMERS</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>SH.FWEEK_PSCAT_SALES_MV</code>.
     */
    public static final FweekPscatSalesMv FWEEK_PSCAT_SALES_MV = FweekPscatSalesMv.FWEEK_PSCAT_SALES_MV;

    /**
     * The table <code>SH.PRODUCTS</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>SH.PROFITS</code>.
     */
    public static final Profits PROFITS = Profits.PROFITS;

    /**
     * The table <code>SH.PROMOTIONS</code>.
     */
    public static final Promotions PROMOTIONS = Promotions.PROMOTIONS;

    /**
     * The table <code>SH.SALES</code>.
     */
    public static final Sales SALES = Sales.SALES;

    /**
     * The table <code>SH.SUPPLEMENTARY_DEMOGRAPHICS</code>.
     */
    public static final SupplementaryDemographics SUPPLEMENTARY_DEMOGRAPHICS =
            SupplementaryDemographics.SUPPLEMENTARY_DEMOGRAPHICS;

    /**
     * The table <code>SH.TIMES</code>.
     */
    public static final Times TIMES = Times.TIMES;
}
