package com.github.jinahya.oracle.sample.schemas.co.data;

import com.github.jinahya.oracle.sample.schemas.co.Customer;
import com.github.jinahya.oracle.sample.schemas.co.Customer_;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * A repository for {@link Customer}, the {@code CUSTOMERS} table of the Customer Orders schema.
 * <p>
 * The id is a {@link Long} generated by the database ({@code GenerationType.IDENTITY}), so a newly constructed customer
 * is saved with no id, and the id is set on the saved instance.
 * <p>
 * {@link JpaSpecificationExecutor} is here for criteria queries. Name the attributes through the generated static
 * metamodel rather than by string, for example
 * {@code (root, query, builder) -> builder.equal(root.get(Customer_.fullName), name)}.
 *
 * @see Customer
 * @see Customer_
 */
@Repository
public interface CustomerRepository
    extends JpaRepository<Customer, Long>,
    JpaSpecificationExecutor<Customer> {

  /**
   * Finds the customer with the specified value of {@link Customer_#EMAIL_ADDRESS} attribute.
   * <p>
   * The address is the customer's business key: {@code EMAIL_ADDRESS} is mapped {@code unique}, and it is what
   * {@link Customer#equals(Object)} compares. So there is at most one match, and an {@link Optional} return is safe.
   * The comparison is the database's, which is case-sensitive on Oracle by default.
   *
   * @param emailAddress the value of the {@link Customer_#EMAIL_ADDRESS} attribute to match.
   * @return the customer with {@code emailAddress}, or an empty optional if there is none.
   */
  Optional<Customer> findByEmailAddress(String emailAddress);
}
